import { describe, expect, it } from "vitest";
import { deriveCleanText, detectInboundQuarantineReason } from "./inbound-security";
import { parseInboundEmailData } from "./inbound";

describe("inbound security", () => {
  it("blocks messages generated by the relay itself", () => {
    const message = parseInboundEmailData({
      from: "Solicitações <chamados@chamados.poolflux.app>",
      headers: {},
    });
    expect(detectInboundQuarantineReason(message, "chamados.poolflux.app")).toBe(
      "system_sender_loop",
    );
  });

  it("blocks autoresponders", () => {
    const message = parseInboundEmailData({
      from: "user@example.com",
      headers: { "Auto-Submitted": "auto-replied" },
    });
    expect(detectInboundQuarantineReason(message, "chamados.poolflux.app")).toBe(
      "automated_message",
    );
  });

  it("keeps the original available while deriving a concise text", () => {
    expect(deriveCleanText("Resposta atual\n\nOn yesterday, A wrote:\n> histórico")).toBe(
      "Resposta atual",
    );
  });
});
