/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DefinirSenhaRouteImport } from './routes/definir-senha'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as FSlugRouteImport } from './routes/f.$slug'
import { Route as EventoSucessoRouteImport } from './routes/evento.sucesso'
import { Route as EventoPendenteRouteImport } from './routes/evento.pendente'
import { Route as EventoFalhaRouteImport } from './routes/evento.falha'
import { Route as EventoCheckoutRouteImport } from './routes/evento.checkout'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedVisaoRep2RouteImport } from './routes/_authenticated/visao-rep-2'
import { Route as AuthenticatedVisaoRepRouteImport } from './routes/_authenticated/visao-rep'
import { Route as AuthenticatedTermosDeUsoRouteImport } from './routes/_authenticated/termos-de-uso'
import { Route as AuthenticatedRoteirosRouteImport } from './routes/_authenticated/roteiros'
import { Route as AuthenticatedProjecaoRouteImport } from './routes/_authenticated/projecao'
import { Route as AuthenticatedPriceRouteImport } from './routes/_authenticated/price'
import { Route as AuthenticatedPerspectivasRouteImport } from './routes/_authenticated/perspectivas'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedNovoCorpRouteImport } from './routes/_authenticated/novo-corp'
import { Route as AuthenticatedNdaRouteImport } from './routes/_authenticated/nda'
import { Route as AuthenticatedFamiliasRouteImport } from './routes/_authenticated/familias'
import { Route as AuthenticatedEmpresasRouteImport } from './routes/_authenticated/empresas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompilacoesRouteImport } from './routes/_authenticated/compilacoes'
import { Route as AuthenticatedAgentesRouteImport } from './routes/_authenticated/agentes'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAceiteTermosRouteImport } from './routes/_authenticated/aceite-termos'
import { Route as AuthenticatedTarefasIndexRouteImport } from './routes/_authenticated/tarefas.index'
import { Route as AuthenticatedRepresentantesIndexRouteImport } from './routes/_authenticated/representantes.index'
import { Route as AuthenticatedProdutosIndexRouteImport } from './routes/_authenticated/produtos.index'
import { Route as AuthenticatedPriceIndexRouteImport } from './routes/_authenticated/price.index'
import { Route as AuthenticatedImersoesIndexRouteImport } from './routes/_authenticated/imersoes.index'
import { Route as AuthenticatedFormsIndexRouteImport } from './routes/_authenticated/forms.index'
import { Route as AuthenticatedFontesIndexRouteImport } from './routes/_authenticated/fontes.index'
import { Route as AuthenticatedEntrevistasIndexRouteImport } from './routes/_authenticated/entrevistas.index'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicBackupToDriveRouteImport } from './routes/api/public/backup-to-drive'
import { Route as ApiPublicBackupRunRouteImport } from './routes/api/public/backup-run'
import { Route as ApiPublicBackupDownloadRouteImport } from './routes/api/public/backup-download'
import { Route as ApiPublicBackupCodigoRouteImport } from './routes/api/public/backup-codigo'
import { Route as ApiPublicBackupAuditRouteImport } from './routes/api/public/backup-audit'
import { Route as AuthenticatedSinteseTiposRouteImport } from './routes/_authenticated/sintese.tipos'
import { Route as AuthenticatedRepresentantesPerformanceRouteImport } from './routes/_authenticated/representantes.performance'
import { Route as AuthenticatedPriceTabelasRouteImport } from './routes/_authenticated/price.tabelas'
import { Route as AuthenticatedPriceCompetidoresRouteImport } from './routes/_authenticated/price.competidores'
import { Route as AuthenticatedPriceComparativosRouteImport } from './routes/_authenticated/price.comparativos'
import { Route as AuthenticatedImersoesNovaRouteImport } from './routes/_authenticated/imersoes.nova'
import { Route as AuthenticatedImersoesIdRouteImport } from './routes/_authenticated/imersoes.$id'
import { Route as AuthenticatedFormsIdRouteImport } from './routes/_authenticated/forms.$id'
import { Route as AuthenticatedFontesIdRouteImport } from './routes/_authenticated/fontes.$id'
import { Route as AuthenticatedEntrevistasNovaRouteImport } from './routes/_authenticated/entrevistas.nova'
import { Route as AuthenticatedEntrevistasIdRouteImport } from './routes/_authenticated/entrevistas.$id'
import { Route as AuthenticatedClientesNovoRouteImport } from './routes/_authenticated/clientes.novo'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes.$id'
import { Route as AuthenticatedClientesBiBatchRepIdRouteImport } from './routes/_authenticated/clientes-bi-batch.$repId'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminPermissoesRouteImport } from './routes/_authenticated/admin.permissoes'
import { Route as AuthenticatedAdminMfaRecuperacaoRouteImport } from './routes/_authenticated/admin.mfa-recuperacao'
import { Route as AuthenticatedAdminMfaPoliticaRouteImport } from './routes/_authenticated/admin.mfa-politica'
import { Route as AuthenticatedAdminMfaRouteImport } from './routes/_authenticated/admin.mfa'
import { Route as AuthenticatedAdminLgpdRouteImport } from './routes/_authenticated/admin.lgpd'
import { Route as AuthenticatedAdminGeradorPerformanceRouteImport } from './routes/_authenticated/admin.gerador-performance'
import { Route as AuthenticatedAdminEventoCheckoutTesteRouteImport } from './routes/_authenticated/admin.evento-checkout-teste'
import { Route as AuthenticatedAdminCriteriosSegurancaRouteImport } from './routes/_authenticated/admin.criterios-seguranca'
import { Route as AuthenticatedAdminConformidadeRouteImport } from './routes/_authenticated/admin.conformidade'
import { Route as AuthenticatedAdminBackupRouteImport } from './routes/_authenticated/admin.backup'
import { Route as AuthenticatedAdminAuditoriaSegurancaRouteImport } from './routes/_authenticated/admin.auditoria-seguranca'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicMpWebhookRouteImport } from './routes/api/public/mp/webhook'
import { Route as ApiPublicMpCreatePreferenceRouteImport } from './routes/api/public/mp/create-preference'
import { Route as ApiPublicHooksWeeklySecurityAuditRouteImport } from './routes/api/public/hooks/weekly-security-audit'
import { Route as ApiPublicHooksMfaDeadlineCheckRouteImport } from './routes/api/public/hooks/mfa-deadline-check'
import { Route as AuthenticatedTarefasBBoardIdRouteImport } from './routes/_authenticated/tarefas.b.$boardId'
import { Route as AuthenticatedPermissoesTypeIdRouteImport } from './routes/_authenticated/permissoes.$type.$id'
import { Route as AuthenticatedEntrevistasIdSessaoRouteImport } from './routes/_authenticated/entrevistas.$id.sessao'
import { Route as AuthenticatedClientesIdEditarRouteImport } from './routes/_authenticated/clientes.$id.editar'
import { Route as AuthenticatedClientesBiRepIdRazaoRouteImport } from './routes/_authenticated/clientes-bi.$repId.$razao'
import { Route as ApiPublicMpTestWebhookRouteImport } from './routes/api/public/mp/test/webhook'
import { Route as ApiPublicMpTestCreatePreferenceRouteImport } from './routes/api/public/mp/test/create-preference'
import { Route as AuthenticatedClientesBiCompararRepIdRazaoRouteImport } from './routes/_authenticated/clientes-bi.comparar.$repId.$razao'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DefinirSenhaRoute = DefinirSenhaRouteImport.update({
  id: '/definir-senha',
  path: '/definir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FSlugRoute = FSlugRouteImport.update({
  id: '/f/$slug',
  path: '/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventoSucessoRoute = EventoSucessoRouteImport.update({
  id: '/evento/sucesso',
  path: '/evento/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const EventoPendenteRoute = EventoPendenteRouteImport.update({
  id: '/evento/pendente',
  path: '/evento/pendente',
  getParentRoute: () => rootRouteImport,
} as any)
const EventoFalhaRoute = EventoFalhaRouteImport.update({
  id: '/evento/falha',
  path: '/evento/falha',
  getParentRoute: () => rootRouteImport,
} as any)
const EventoCheckoutRoute = EventoCheckoutRouteImport.update({
  id: '/evento/checkout',
  path: '/evento/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVisaoRep2Route = AuthenticatedVisaoRep2RouteImport.update({
  id: '/visao-rep-2',
  path: '/visao-rep-2',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisaoRepRoute = AuthenticatedVisaoRepRouteImport.update({
  id: '/visao-rep',
  path: '/visao-rep',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTermosDeUsoRoute =
  AuthenticatedTermosDeUsoRouteImport.update({
    id: '/termos-de-uso',
    path: '/termos-de-uso',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoteirosRoute = AuthenticatedRoteirosRouteImport.update({
  id: '/roteiros',
  path: '/roteiros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjecaoRoute = AuthenticatedProjecaoRouteImport.update({
  id: '/projecao',
  path: '/projecao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPriceRoute = AuthenticatedPriceRouteImport.update({
  id: '/price',
  path: '/price',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerspectivasRoute =
  AuthenticatedPerspectivasRouteImport.update({
    id: '/perspectivas',
    path: '/perspectivas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNovoCorpRoute = AuthenticatedNovoCorpRouteImport.update({
  id: '/novo-corp',
  path: '/novo-corp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNdaRoute = AuthenticatedNdaRouteImport.update({
  id: '/nda',
  path: '/nda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFamiliasRoute = AuthenticatedFamiliasRouteImport.update({
  id: '/familias',
  path: '/familias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpresasRoute = AuthenticatedEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompilacoesRoute =
  AuthenticatedCompilacoesRouteImport.update({
    id: '/compilacoes',
    path: '/compilacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgentesRoute = AuthenticatedAgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAceiteTermosRoute =
  AuthenticatedAceiteTermosRouteImport.update({
    id: '/aceite-termos',
    path: '/aceite-termos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTarefasIndexRoute =
  AuthenticatedTarefasIndexRouteImport.update({
    id: '/tarefas/',
    path: '/tarefas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRepresentantesIndexRoute =
  AuthenticatedRepresentantesIndexRouteImport.update({
    id: '/representantes/',
    path: '/representantes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProdutosIndexRoute =
  AuthenticatedProdutosIndexRouteImport.update({
    id: '/produtos/',
    path: '/produtos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPriceIndexRoute = AuthenticatedPriceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedPriceRoute,
} as any)
const AuthenticatedImersoesIndexRoute =
  AuthenticatedImersoesIndexRouteImport.update({
    id: '/imersoes/',
    path: '/imersoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormsIndexRoute = AuthenticatedFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFontesIndexRoute =
  AuthenticatedFontesIndexRouteImport.update({
    id: '/fontes/',
    path: '/fontes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntrevistasIndexRoute =
  AuthenticatedEntrevistasIndexRouteImport.update({
    id: '/entrevistas/',
    path: '/entrevistas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBackupToDriveRoute = ApiPublicBackupToDriveRouteImport.update({
  id: '/api/public/backup-to-drive',
  path: '/api/public/backup-to-drive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBackupRunRoute = ApiPublicBackupRunRouteImport.update({
  id: '/api/public/backup-run',
  path: '/api/public/backup-run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBackupDownloadRoute = ApiPublicBackupDownloadRouteImport.update({
  id: '/api/public/backup-download',
  path: '/api/public/backup-download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBackupCodigoRoute = ApiPublicBackupCodigoRouteImport.update({
  id: '/api/public/backup-codigo',
  path: '/api/public/backup-codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBackupAuditRoute = ApiPublicBackupAuditRouteImport.update({
  id: '/api/public/backup-audit',
  path: '/api/public/backup-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSinteseTiposRoute =
  AuthenticatedSinteseTiposRouteImport.update({
    id: '/sintese/tipos',
    path: '/sintese/tipos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRepresentantesPerformanceRoute =
  AuthenticatedRepresentantesPerformanceRouteImport.update({
    id: '/representantes/performance',
    path: '/representantes/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPriceTabelasRoute =
  AuthenticatedPriceTabelasRouteImport.update({
    id: '/tabelas',
    path: '/tabelas',
    getParentRoute: () => AuthenticatedPriceRoute,
  } as any)
const AuthenticatedPriceCompetidoresRoute =
  AuthenticatedPriceCompetidoresRouteImport.update({
    id: '/competidores',
    path: '/competidores',
    getParentRoute: () => AuthenticatedPriceRoute,
  } as any)
const AuthenticatedPriceComparativosRoute =
  AuthenticatedPriceComparativosRouteImport.update({
    id: '/comparativos',
    path: '/comparativos',
    getParentRoute: () => AuthenticatedPriceRoute,
  } as any)
const AuthenticatedImersoesNovaRoute =
  AuthenticatedImersoesNovaRouteImport.update({
    id: '/imersoes/nova',
    path: '/imersoes/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImersoesIdRoute = AuthenticatedImersoesIdRouteImport.update({
  id: '/imersoes/$id',
  path: '/imersoes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFormsIdRoute = AuthenticatedFormsIdRouteImport.update({
  id: '/forms/$id',
  path: '/forms/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFontesIdRoute = AuthenticatedFontesIdRouteImport.update({
  id: '/fontes/$id',
  path: '/fontes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntrevistasNovaRoute =
  AuthenticatedEntrevistasNovaRouteImport.update({
    id: '/entrevistas/nova',
    path: '/entrevistas/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntrevistasIdRoute =
  AuthenticatedEntrevistasIdRouteImport.update({
    id: '/entrevistas/$id',
    path: '/entrevistas/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesNovoRoute =
  AuthenticatedClientesNovoRouteImport.update({
    id: '/clientes/novo',
    path: '/clientes/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesBiBatchRepIdRoute =
  AuthenticatedClientesBiBatchRepIdRouteImport.update({
    id: '/clientes-bi-batch/$repId',
    path: '/clientes-bi-batch/$repId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPermissoesRoute =
  AuthenticatedAdminPermissoesRouteImport.update({
    id: '/permissoes',
    path: '/permissoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMfaRecuperacaoRoute =
  AuthenticatedAdminMfaRecuperacaoRouteImport.update({
    id: '/mfa-recuperacao',
    path: '/mfa-recuperacao',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMfaPoliticaRoute =
  AuthenticatedAdminMfaPoliticaRouteImport.update({
    id: '/mfa-politica',
    path: '/mfa-politica',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMfaRoute = AuthenticatedAdminMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLgpdRoute = AuthenticatedAdminLgpdRouteImport.update({
  id: '/lgpd',
  path: '/lgpd',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminGeradorPerformanceRoute =
  AuthenticatedAdminGeradorPerformanceRouteImport.update({
    id: '/gerador-performance',
    path: '/gerador-performance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventoCheckoutTesteRoute =
  AuthenticatedAdminEventoCheckoutTesteRouteImport.update({
    id: '/evento-checkout-teste',
    path: '/evento-checkout-teste',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCriteriosSegurancaRoute =
  AuthenticatedAdminCriteriosSegurancaRouteImport.update({
    id: '/criterios-seguranca',
    path: '/criterios-seguranca',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConformidadeRoute =
  AuthenticatedAdminConformidadeRouteImport.update({
    id: '/conformidade',
    path: '/conformidade',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBackupRoute =
  AuthenticatedAdminBackupRouteImport.update({
    id: '/backup',
    path: '/backup',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditoriaSegurancaRoute =
  AuthenticatedAdminAuditoriaSegurancaRouteImport.update({
    id: '/auditoria-seguranca',
    path: '/auditoria-seguranca',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMpWebhookRoute = ApiPublicMpWebhookRouteImport.update({
  id: '/api/public/mp/webhook',
  path: '/api/public/mp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpCreatePreferenceRoute =
  ApiPublicMpCreatePreferenceRouteImport.update({
    id: '/api/public/mp/create-preference',
    path: '/api/public/mp/create-preference',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWeeklySecurityAuditRoute =
  ApiPublicHooksWeeklySecurityAuditRouteImport.update({
    id: '/api/public/hooks/weekly-security-audit',
    path: '/api/public/hooks/weekly-security-audit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMfaDeadlineCheckRoute =
  ApiPublicHooksMfaDeadlineCheckRouteImport.update({
    id: '/api/public/hooks/mfa-deadline-check',
    path: '/api/public/hooks/mfa-deadline-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTarefasBBoardIdRoute =
  AuthenticatedTarefasBBoardIdRouteImport.update({
    id: '/tarefas/b/$boardId',
    path: '/tarefas/b/$boardId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPermissoesTypeIdRoute =
  AuthenticatedPermissoesTypeIdRouteImport.update({
    id: '/permissoes/$type/$id',
    path: '/permissoes/$type/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntrevistasIdSessaoRoute =
  AuthenticatedEntrevistasIdSessaoRouteImport.update({
    id: '/sessao',
    path: '/sessao',
    getParentRoute: () => AuthenticatedEntrevistasIdRoute,
  } as any)
const AuthenticatedClientesIdEditarRoute =
  AuthenticatedClientesIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedClientesIdRoute,
  } as any)
const AuthenticatedClientesBiRepIdRazaoRoute =
  AuthenticatedClientesBiRepIdRazaoRouteImport.update({
    id: '/clientes-bi/$repId/$razao',
    path: '/clientes-bi/$repId/$razao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicMpTestWebhookRoute = ApiPublicMpTestWebhookRouteImport.update({
  id: '/api/public/mp/test/webhook',
  path: '/api/public/mp/test/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpTestCreatePreferenceRoute =
  ApiPublicMpTestCreatePreferenceRouteImport.update({
    id: '/api/public/mp/test/create-preference',
    path: '/api/public/mp/test/create-preference',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedClientesBiCompararRepIdRazaoRoute =
  AuthenticatedClientesBiCompararRepIdRazaoRouteImport.update({
    id: '/clientes-bi/comparar/$repId/$razao',
    path: '/clientes-bi/comparar/$repId/$razao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/aceite-termos': typeof AuthenticatedAceiteTermosRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/agentes': typeof AuthenticatedAgentesRoute
  '/compilacoes': typeof AuthenticatedCompilacoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/familias': typeof AuthenticatedFamiliasRoute
  '/nda': typeof AuthenticatedNdaRoute
  '/novo-corp': typeof AuthenticatedNovoCorpRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/perspectivas': typeof AuthenticatedPerspectivasRoute
  '/price': typeof AuthenticatedPriceRouteWithChildren
  '/projecao': typeof AuthenticatedProjecaoRoute
  '/roteiros': typeof AuthenticatedRoteirosRoute
  '/termos-de-uso': typeof AuthenticatedTermosDeUsoRoute
  '/visao-rep': typeof AuthenticatedVisaoRepRoute
  '/visao-rep-2': typeof AuthenticatedVisaoRep2Route
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/evento/checkout': typeof EventoCheckoutRoute
  '/evento/falha': typeof EventoFalhaRoute
  '/evento/pendente': typeof EventoPendenteRoute
  '/evento/sucesso': typeof EventoSucessoRoute
  '/f/$slug': typeof FSlugRoute
  '/r/$token': typeof RTokenRoute
  '/admin/auditoria-seguranca': typeof AuthenticatedAdminAuditoriaSegurancaRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/conformidade': typeof AuthenticatedAdminConformidadeRoute
  '/admin/criterios-seguranca': typeof AuthenticatedAdminCriteriosSegurancaRoute
  '/admin/evento-checkout-teste': typeof AuthenticatedAdminEventoCheckoutTesteRoute
  '/admin/gerador-performance': typeof AuthenticatedAdminGeradorPerformanceRoute
  '/admin/lgpd': typeof AuthenticatedAdminLgpdRoute
  '/admin/mfa': typeof AuthenticatedAdminMfaRoute
  '/admin/mfa-politica': typeof AuthenticatedAdminMfaPoliticaRoute
  '/admin/mfa-recuperacao': typeof AuthenticatedAdminMfaRecuperacaoRoute
  '/admin/permissoes': typeof AuthenticatedAdminPermissoesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/clientes-bi-batch/$repId': typeof AuthenticatedClientesBiBatchRepIdRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRouteWithChildren
  '/clientes/novo': typeof AuthenticatedClientesNovoRoute
  '/entrevistas/$id': typeof AuthenticatedEntrevistasIdRouteWithChildren
  '/entrevistas/nova': typeof AuthenticatedEntrevistasNovaRoute
  '/fontes/$id': typeof AuthenticatedFontesIdRoute
  '/forms/$id': typeof AuthenticatedFormsIdRoute
  '/imersoes/$id': typeof AuthenticatedImersoesIdRoute
  '/imersoes/nova': typeof AuthenticatedImersoesNovaRoute
  '/price/comparativos': typeof AuthenticatedPriceComparativosRoute
  '/price/competidores': typeof AuthenticatedPriceCompetidoresRoute
  '/price/tabelas': typeof AuthenticatedPriceTabelasRoute
  '/representantes/performance': typeof AuthenticatedRepresentantesPerformanceRoute
  '/sintese/tipos': typeof AuthenticatedSinteseTiposRoute
  '/api/public/backup-audit': typeof ApiPublicBackupAuditRoute
  '/api/public/backup-codigo': typeof ApiPublicBackupCodigoRoute
  '/api/public/backup-download': typeof ApiPublicBackupDownloadRoute
  '/api/public/backup-run': typeof ApiPublicBackupRunRoute
  '/api/public/backup-to-drive': typeof ApiPublicBackupToDriveRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
  '/entrevistas/': typeof AuthenticatedEntrevistasIndexRoute
  '/fontes/': typeof AuthenticatedFontesIndexRoute
  '/forms/': typeof AuthenticatedFormsIndexRoute
  '/imersoes/': typeof AuthenticatedImersoesIndexRoute
  '/price/': typeof AuthenticatedPriceIndexRoute
  '/produtos/': typeof AuthenticatedProdutosIndexRoute
  '/representantes/': typeof AuthenticatedRepresentantesIndexRoute
  '/tarefas/': typeof AuthenticatedTarefasIndexRoute
  '/clientes-bi/$repId/$razao': typeof AuthenticatedClientesBiRepIdRazaoRoute
  '/clientes/$id/editar': typeof AuthenticatedClientesIdEditarRoute
  '/entrevistas/$id/sessao': typeof AuthenticatedEntrevistasIdSessaoRoute
  '/permissoes/$type/$id': typeof AuthenticatedPermissoesTypeIdRoute
  '/tarefas/b/$boardId': typeof AuthenticatedTarefasBBoardIdRoute
  '/api/public/hooks/mfa-deadline-check': typeof ApiPublicHooksMfaDeadlineCheckRoute
  '/api/public/hooks/weekly-security-audit': typeof ApiPublicHooksWeeklySecurityAuditRoute
  '/api/public/mp/create-preference': typeof ApiPublicMpCreatePreferenceRoute
  '/api/public/mp/webhook': typeof ApiPublicMpWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/clientes-bi/comparar/$repId/$razao': typeof AuthenticatedClientesBiCompararRepIdRazaoRoute
  '/api/public/mp/test/create-preference': typeof ApiPublicMpTestCreatePreferenceRoute
  '/api/public/mp/test/webhook': typeof ApiPublicMpTestWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/aceite-termos': typeof AuthenticatedAceiteTermosRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/agentes': typeof AuthenticatedAgentesRoute
  '/compilacoes': typeof AuthenticatedCompilacoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/familias': typeof AuthenticatedFamiliasRoute
  '/nda': typeof AuthenticatedNdaRoute
  '/novo-corp': typeof AuthenticatedNovoCorpRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/perspectivas': typeof AuthenticatedPerspectivasRoute
  '/projecao': typeof AuthenticatedProjecaoRoute
  '/roteiros': typeof AuthenticatedRoteirosRoute
  '/termos-de-uso': typeof AuthenticatedTermosDeUsoRoute
  '/visao-rep': typeof AuthenticatedVisaoRepRoute
  '/visao-rep-2': typeof AuthenticatedVisaoRep2Route
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/evento/checkout': typeof EventoCheckoutRoute
  '/evento/falha': typeof EventoFalhaRoute
  '/evento/pendente': typeof EventoPendenteRoute
  '/evento/sucesso': typeof EventoSucessoRoute
  '/f/$slug': typeof FSlugRoute
  '/r/$token': typeof RTokenRoute
  '/admin/auditoria-seguranca': typeof AuthenticatedAdminAuditoriaSegurancaRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/conformidade': typeof AuthenticatedAdminConformidadeRoute
  '/admin/criterios-seguranca': typeof AuthenticatedAdminCriteriosSegurancaRoute
  '/admin/evento-checkout-teste': typeof AuthenticatedAdminEventoCheckoutTesteRoute
  '/admin/gerador-performance': typeof AuthenticatedAdminGeradorPerformanceRoute
  '/admin/lgpd': typeof AuthenticatedAdminLgpdRoute
  '/admin/mfa': typeof AuthenticatedAdminMfaRoute
  '/admin/mfa-politica': typeof AuthenticatedAdminMfaPoliticaRoute
  '/admin/mfa-recuperacao': typeof AuthenticatedAdminMfaRecuperacaoRoute
  '/admin/permissoes': typeof AuthenticatedAdminPermissoesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/clientes-bi-batch/$repId': typeof AuthenticatedClientesBiBatchRepIdRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRouteWithChildren
  '/clientes/novo': typeof AuthenticatedClientesNovoRoute
  '/entrevistas/$id': typeof AuthenticatedEntrevistasIdRouteWithChildren
  '/entrevistas/nova': typeof AuthenticatedEntrevistasNovaRoute
  '/fontes/$id': typeof AuthenticatedFontesIdRoute
  '/forms/$id': typeof AuthenticatedFormsIdRoute
  '/imersoes/$id': typeof AuthenticatedImersoesIdRoute
  '/imersoes/nova': typeof AuthenticatedImersoesNovaRoute
  '/price/comparativos': typeof AuthenticatedPriceComparativosRoute
  '/price/competidores': typeof AuthenticatedPriceCompetidoresRoute
  '/price/tabelas': typeof AuthenticatedPriceTabelasRoute
  '/representantes/performance': typeof AuthenticatedRepresentantesPerformanceRoute
  '/sintese/tipos': typeof AuthenticatedSinteseTiposRoute
  '/api/public/backup-audit': typeof ApiPublicBackupAuditRoute
  '/api/public/backup-codigo': typeof ApiPublicBackupCodigoRoute
  '/api/public/backup-download': typeof ApiPublicBackupDownloadRoute
  '/api/public/backup-run': typeof ApiPublicBackupRunRoute
  '/api/public/backup-to-drive': typeof ApiPublicBackupToDriveRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/entrevistas': typeof AuthenticatedEntrevistasIndexRoute
  '/fontes': typeof AuthenticatedFontesIndexRoute
  '/forms': typeof AuthenticatedFormsIndexRoute
  '/imersoes': typeof AuthenticatedImersoesIndexRoute
  '/price': typeof AuthenticatedPriceIndexRoute
  '/produtos': typeof AuthenticatedProdutosIndexRoute
  '/representantes': typeof AuthenticatedRepresentantesIndexRoute
  '/tarefas': typeof AuthenticatedTarefasIndexRoute
  '/clientes-bi/$repId/$razao': typeof AuthenticatedClientesBiRepIdRazaoRoute
  '/clientes/$id/editar': typeof AuthenticatedClientesIdEditarRoute
  '/entrevistas/$id/sessao': typeof AuthenticatedEntrevistasIdSessaoRoute
  '/permissoes/$type/$id': typeof AuthenticatedPermissoesTypeIdRoute
  '/tarefas/b/$boardId': typeof AuthenticatedTarefasBBoardIdRoute
  '/api/public/hooks/mfa-deadline-check': typeof ApiPublicHooksMfaDeadlineCheckRoute
  '/api/public/hooks/weekly-security-audit': typeof ApiPublicHooksWeeklySecurityAuditRoute
  '/api/public/mp/create-preference': typeof ApiPublicMpCreatePreferenceRoute
  '/api/public/mp/webhook': typeof ApiPublicMpWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/clientes-bi/comparar/$repId/$razao': typeof AuthenticatedClientesBiCompararRepIdRazaoRoute
  '/api/public/mp/test/create-preference': typeof ApiPublicMpTestCreatePreferenceRoute
  '/api/public/mp/test/webhook': typeof ApiPublicMpTestWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/aceite-termos': typeof AuthenticatedAceiteTermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/agentes': typeof AuthenticatedAgentesRoute
  '/_authenticated/compilacoes': typeof AuthenticatedCompilacoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/empresas': typeof AuthenticatedEmpresasRoute
  '/_authenticated/familias': typeof AuthenticatedFamiliasRoute
  '/_authenticated/nda': typeof AuthenticatedNdaRoute
  '/_authenticated/novo-corp': typeof AuthenticatedNovoCorpRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/perspectivas': typeof AuthenticatedPerspectivasRoute
  '/_authenticated/price': typeof AuthenticatedPriceRouteWithChildren
  '/_authenticated/projecao': typeof AuthenticatedProjecaoRoute
  '/_authenticated/roteiros': typeof AuthenticatedRoteirosRoute
  '/_authenticated/termos-de-uso': typeof AuthenticatedTermosDeUsoRoute
  '/_authenticated/visao-rep': typeof AuthenticatedVisaoRepRoute
  '/_authenticated/visao-rep-2': typeof AuthenticatedVisaoRep2Route
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/evento/checkout': typeof EventoCheckoutRoute
  '/evento/falha': typeof EventoFalhaRoute
  '/evento/pendente': typeof EventoPendenteRoute
  '/evento/sucesso': typeof EventoSucessoRoute
  '/f/$slug': typeof FSlugRoute
  '/r/$token': typeof RTokenRoute
  '/_authenticated/admin/auditoria-seguranca': typeof AuthenticatedAdminAuditoriaSegurancaRoute
  '/_authenticated/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/_authenticated/admin/conformidade': typeof AuthenticatedAdminConformidadeRoute
  '/_authenticated/admin/criterios-seguranca': typeof AuthenticatedAdminCriteriosSegurancaRoute
  '/_authenticated/admin/evento-checkout-teste': typeof AuthenticatedAdminEventoCheckoutTesteRoute
  '/_authenticated/admin/gerador-performance': typeof AuthenticatedAdminGeradorPerformanceRoute
  '/_authenticated/admin/lgpd': typeof AuthenticatedAdminLgpdRoute
  '/_authenticated/admin/mfa': typeof AuthenticatedAdminMfaRoute
  '/_authenticated/admin/mfa-politica': typeof AuthenticatedAdminMfaPoliticaRoute
  '/_authenticated/admin/mfa-recuperacao': typeof AuthenticatedAdminMfaRecuperacaoRoute
  '/_authenticated/admin/permissoes': typeof AuthenticatedAdminPermissoesRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/clientes-bi-batch/$repId': typeof AuthenticatedClientesBiBatchRepIdRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRouteWithChildren
  '/_authenticated/clientes/novo': typeof AuthenticatedClientesNovoRoute
  '/_authenticated/entrevistas/$id': typeof AuthenticatedEntrevistasIdRouteWithChildren
  '/_authenticated/entrevistas/nova': typeof AuthenticatedEntrevistasNovaRoute
  '/_authenticated/fontes/$id': typeof AuthenticatedFontesIdRoute
  '/_authenticated/forms/$id': typeof AuthenticatedFormsIdRoute
  '/_authenticated/imersoes/$id': typeof AuthenticatedImersoesIdRoute
  '/_authenticated/imersoes/nova': typeof AuthenticatedImersoesNovaRoute
  '/_authenticated/price/comparativos': typeof AuthenticatedPriceComparativosRoute
  '/_authenticated/price/competidores': typeof AuthenticatedPriceCompetidoresRoute
  '/_authenticated/price/tabelas': typeof AuthenticatedPriceTabelasRoute
  '/_authenticated/representantes/performance': typeof AuthenticatedRepresentantesPerformanceRoute
  '/_authenticated/sintese/tipos': typeof AuthenticatedSinteseTiposRoute
  '/api/public/backup-audit': typeof ApiPublicBackupAuditRoute
  '/api/public/backup-codigo': typeof ApiPublicBackupCodigoRoute
  '/api/public/backup-download': typeof ApiPublicBackupDownloadRoute
  '/api/public/backup-run': typeof ApiPublicBackupRunRoute
  '/api/public/backup-to-drive': typeof ApiPublicBackupToDriveRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/_authenticated/entrevistas/': typeof AuthenticatedEntrevistasIndexRoute
  '/_authenticated/fontes/': typeof AuthenticatedFontesIndexRoute
  '/_authenticated/forms/': typeof AuthenticatedFormsIndexRoute
  '/_authenticated/imersoes/': typeof AuthenticatedImersoesIndexRoute
  '/_authenticated/price/': typeof AuthenticatedPriceIndexRoute
  '/_authenticated/produtos/': typeof AuthenticatedProdutosIndexRoute
  '/_authenticated/representantes/': typeof AuthenticatedRepresentantesIndexRoute
  '/_authenticated/tarefas/': typeof AuthenticatedTarefasIndexRoute
  '/_authenticated/clientes-bi/$repId/$razao': typeof AuthenticatedClientesBiRepIdRazaoRoute
  '/_authenticated/clientes/$id/editar': typeof AuthenticatedClientesIdEditarRoute
  '/_authenticated/entrevistas/$id/sessao': typeof AuthenticatedEntrevistasIdSessaoRoute
  '/_authenticated/permissoes/$type/$id': typeof AuthenticatedPermissoesTypeIdRoute
  '/_authenticated/tarefas/b/$boardId': typeof AuthenticatedTarefasBBoardIdRoute
  '/api/public/hooks/mfa-deadline-check': typeof ApiPublicHooksMfaDeadlineCheckRoute
  '/api/public/hooks/weekly-security-audit': typeof ApiPublicHooksWeeklySecurityAuditRoute
  '/api/public/mp/create-preference': typeof ApiPublicMpCreatePreferenceRoute
  '/api/public/mp/webhook': typeof ApiPublicMpWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_authenticated/clientes-bi/comparar/$repId/$razao': typeof AuthenticatedClientesBiCompararRepIdRazaoRoute
  '/api/public/mp/test/create-preference': typeof ApiPublicMpTestCreatePreferenceRoute
  '/api/public/mp/test/webhook': typeof ApiPublicMpTestWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/definir-senha'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/aceite-termos'
    | '/admin'
    | '/agentes'
    | '/compilacoes'
    | '/dashboard'
    | '/empresas'
    | '/familias'
    | '/nda'
    | '/novo-corp'
    | '/perfil'
    | '/perspectivas'
    | '/price'
    | '/projecao'
    | '/roteiros'
    | '/termos-de-uso'
    | '/visao-rep'
    | '/visao-rep-2'
    | '/email/unsubscribe'
    | '/evento/checkout'
    | '/evento/falha'
    | '/evento/pendente'
    | '/evento/sucesso'
    | '/f/$slug'
    | '/r/$token'
    | '/admin/auditoria-seguranca'
    | '/admin/backup'
    | '/admin/conformidade'
    | '/admin/criterios-seguranca'
    | '/admin/evento-checkout-teste'
    | '/admin/gerador-performance'
    | '/admin/lgpd'
    | '/admin/mfa'
    | '/admin/mfa-politica'
    | '/admin/mfa-recuperacao'
    | '/admin/permissoes'
    | '/admin/usuarios'
    | '/clientes-bi-batch/$repId'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/entrevistas/$id'
    | '/entrevistas/nova'
    | '/fontes/$id'
    | '/forms/$id'
    | '/imersoes/$id'
    | '/imersoes/nova'
    | '/price/comparativos'
    | '/price/competidores'
    | '/price/tabelas'
    | '/representantes/performance'
    | '/sintese/tipos'
    | '/api/public/backup-audit'
    | '/api/public/backup-codigo'
    | '/api/public/backup-download'
    | '/api/public/backup-run'
    | '/api/public/backup-to-drive'
    | '/lovable/email/suppression'
    | '/clientes/'
    | '/entrevistas/'
    | '/fontes/'
    | '/forms/'
    | '/imersoes/'
    | '/price/'
    | '/produtos/'
    | '/representantes/'
    | '/tarefas/'
    | '/clientes-bi/$repId/$razao'
    | '/clientes/$id/editar'
    | '/entrevistas/$id/sessao'
    | '/permissoes/$type/$id'
    | '/tarefas/b/$boardId'
    | '/api/public/hooks/mfa-deadline-check'
    | '/api/public/hooks/weekly-security-audit'
    | '/api/public/mp/create-preference'
    | '/api/public/mp/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/clientes-bi/comparar/$repId/$razao'
    | '/api/public/mp/test/create-preference'
    | '/api/public/mp/test/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/definir-senha'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/aceite-termos'
    | '/admin'
    | '/agentes'
    | '/compilacoes'
    | '/dashboard'
    | '/empresas'
    | '/familias'
    | '/nda'
    | '/novo-corp'
    | '/perfil'
    | '/perspectivas'
    | '/projecao'
    | '/roteiros'
    | '/termos-de-uso'
    | '/visao-rep'
    | '/visao-rep-2'
    | '/email/unsubscribe'
    | '/evento/checkout'
    | '/evento/falha'
    | '/evento/pendente'
    | '/evento/sucesso'
    | '/f/$slug'
    | '/r/$token'
    | '/admin/auditoria-seguranca'
    | '/admin/backup'
    | '/admin/conformidade'
    | '/admin/criterios-seguranca'
    | '/admin/evento-checkout-teste'
    | '/admin/gerador-performance'
    | '/admin/lgpd'
    | '/admin/mfa'
    | '/admin/mfa-politica'
    | '/admin/mfa-recuperacao'
    | '/admin/permissoes'
    | '/admin/usuarios'
    | '/clientes-bi-batch/$repId'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/entrevistas/$id'
    | '/entrevistas/nova'
    | '/fontes/$id'
    | '/forms/$id'
    | '/imersoes/$id'
    | '/imersoes/nova'
    | '/price/comparativos'
    | '/price/competidores'
    | '/price/tabelas'
    | '/representantes/performance'
    | '/sintese/tipos'
    | '/api/public/backup-audit'
    | '/api/public/backup-codigo'
    | '/api/public/backup-download'
    | '/api/public/backup-run'
    | '/api/public/backup-to-drive'
    | '/lovable/email/suppression'
    | '/clientes'
    | '/entrevistas'
    | '/fontes'
    | '/forms'
    | '/imersoes'
    | '/price'
    | '/produtos'
    | '/representantes'
    | '/tarefas'
    | '/clientes-bi/$repId/$razao'
    | '/clientes/$id/editar'
    | '/entrevistas/$id/sessao'
    | '/permissoes/$type/$id'
    | '/tarefas/b/$boardId'
    | '/api/public/hooks/mfa-deadline-check'
    | '/api/public/hooks/weekly-security-audit'
    | '/api/public/mp/create-preference'
    | '/api/public/mp/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/clientes-bi/comparar/$repId/$razao'
    | '/api/public/mp/test/create-preference'
    | '/api/public/mp/test/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/definir-senha'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/_authenticated/aceite-termos'
    | '/_authenticated/admin'
    | '/_authenticated/agentes'
    | '/_authenticated/compilacoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/empresas'
    | '/_authenticated/familias'
    | '/_authenticated/nda'
    | '/_authenticated/novo-corp'
    | '/_authenticated/perfil'
    | '/_authenticated/perspectivas'
    | '/_authenticated/price'
    | '/_authenticated/projecao'
    | '/_authenticated/roteiros'
    | '/_authenticated/termos-de-uso'
    | '/_authenticated/visao-rep'
    | '/_authenticated/visao-rep-2'
    | '/email/unsubscribe'
    | '/evento/checkout'
    | '/evento/falha'
    | '/evento/pendente'
    | '/evento/sucesso'
    | '/f/$slug'
    | '/r/$token'
    | '/_authenticated/admin/auditoria-seguranca'
    | '/_authenticated/admin/backup'
    | '/_authenticated/admin/conformidade'
    | '/_authenticated/admin/criterios-seguranca'
    | '/_authenticated/admin/evento-checkout-teste'
    | '/_authenticated/admin/gerador-performance'
    | '/_authenticated/admin/lgpd'
    | '/_authenticated/admin/mfa'
    | '/_authenticated/admin/mfa-politica'
    | '/_authenticated/admin/mfa-recuperacao'
    | '/_authenticated/admin/permissoes'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/clientes-bi-batch/$repId'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/clientes/novo'
    | '/_authenticated/entrevistas/$id'
    | '/_authenticated/entrevistas/nova'
    | '/_authenticated/fontes/$id'
    | '/_authenticated/forms/$id'
    | '/_authenticated/imersoes/$id'
    | '/_authenticated/imersoes/nova'
    | '/_authenticated/price/comparativos'
    | '/_authenticated/price/competidores'
    | '/_authenticated/price/tabelas'
    | '/_authenticated/representantes/performance'
    | '/_authenticated/sintese/tipos'
    | '/api/public/backup-audit'
    | '/api/public/backup-codigo'
    | '/api/public/backup-download'
    | '/api/public/backup-run'
    | '/api/public/backup-to-drive'
    | '/lovable/email/suppression'
    | '/_authenticated/clientes/'
    | '/_authenticated/entrevistas/'
    | '/_authenticated/fontes/'
    | '/_authenticated/forms/'
    | '/_authenticated/imersoes/'
    | '/_authenticated/price/'
    | '/_authenticated/produtos/'
    | '/_authenticated/representantes/'
    | '/_authenticated/tarefas/'
    | '/_authenticated/clientes-bi/$repId/$razao'
    | '/_authenticated/clientes/$id/editar'
    | '/_authenticated/entrevistas/$id/sessao'
    | '/_authenticated/permissoes/$type/$id'
    | '/_authenticated/tarefas/b/$boardId'
    | '/api/public/hooks/mfa-deadline-check'
    | '/api/public/hooks/weekly-security-audit'
    | '/api/public/mp/create-preference'
    | '/api/public/mp/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_authenticated/clientes-bi/comparar/$repId/$razao'
    | '/api/public/mp/test/create-preference'
    | '/api/public/mp/test/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DefinirSenhaRoute: typeof DefinirSenhaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  EventoCheckoutRoute: typeof EventoCheckoutRoute
  EventoFalhaRoute: typeof EventoFalhaRoute
  EventoPendenteRoute: typeof EventoPendenteRoute
  EventoSucessoRoute: typeof EventoSucessoRoute
  FSlugRoute: typeof FSlugRoute
  RTokenRoute: typeof RTokenRoute
  ApiPublicBackupAuditRoute: typeof ApiPublicBackupAuditRoute
  ApiPublicBackupCodigoRoute: typeof ApiPublicBackupCodigoRoute
  ApiPublicBackupDownloadRoute: typeof ApiPublicBackupDownloadRoute
  ApiPublicBackupRunRoute: typeof ApiPublicBackupRunRoute
  ApiPublicBackupToDriveRoute: typeof ApiPublicBackupToDriveRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksMfaDeadlineCheckRoute: typeof ApiPublicHooksMfaDeadlineCheckRoute
  ApiPublicHooksWeeklySecurityAuditRoute: typeof ApiPublicHooksWeeklySecurityAuditRoute
  ApiPublicMpCreatePreferenceRoute: typeof ApiPublicMpCreatePreferenceRoute
  ApiPublicMpWebhookRoute: typeof ApiPublicMpWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
  ApiPublicMpTestCreatePreferenceRoute: typeof ApiPublicMpTestCreatePreferenceRoute
  ApiPublicMpTestWebhookRoute: typeof ApiPublicMpTestWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/definir-senha': {
      id: '/definir-senha'
      path: '/definir-senha'
      fullPath: '/definir-senha'
      preLoaderRoute: typeof DefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$slug': {
      id: '/f/$slug'
      path: '/f/$slug'
      fullPath: '/f/$slug'
      preLoaderRoute: typeof FSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evento/sucesso': {
      id: '/evento/sucesso'
      path: '/evento/sucesso'
      fullPath: '/evento/sucesso'
      preLoaderRoute: typeof EventoSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evento/pendente': {
      id: '/evento/pendente'
      path: '/evento/pendente'
      fullPath: '/evento/pendente'
      preLoaderRoute: typeof EventoPendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evento/falha': {
      id: '/evento/falha'
      path: '/evento/falha'
      fullPath: '/evento/falha'
      preLoaderRoute: typeof EventoFalhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evento/checkout': {
      id: '/evento/checkout'
      path: '/evento/checkout'
      fullPath: '/evento/checkout'
      preLoaderRoute: typeof EventoCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/visao-rep-2': {
      id: '/_authenticated/visao-rep-2'
      path: '/visao-rep-2'
      fullPath: '/visao-rep-2'
      preLoaderRoute: typeof AuthenticatedVisaoRep2RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visao-rep': {
      id: '/_authenticated/visao-rep'
      path: '/visao-rep'
      fullPath: '/visao-rep'
      preLoaderRoute: typeof AuthenticatedVisaoRepRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/termos-de-uso': {
      id: '/_authenticated/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof AuthenticatedTermosDeUsoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roteiros': {
      id: '/_authenticated/roteiros'
      path: '/roteiros'
      fullPath: '/roteiros'
      preLoaderRoute: typeof AuthenticatedRoteirosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projecao': {
      id: '/_authenticated/projecao'
      path: '/projecao'
      fullPath: '/projecao'
      preLoaderRoute: typeof AuthenticatedProjecaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/price': {
      id: '/_authenticated/price'
      path: '/price'
      fullPath: '/price'
      preLoaderRoute: typeof AuthenticatedPriceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perspectivas': {
      id: '/_authenticated/perspectivas'
      path: '/perspectivas'
      fullPath: '/perspectivas'
      preLoaderRoute: typeof AuthenticatedPerspectivasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/novo-corp': {
      id: '/_authenticated/novo-corp'
      path: '/novo-corp'
      fullPath: '/novo-corp'
      preLoaderRoute: typeof AuthenticatedNovoCorpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nda': {
      id: '/_authenticated/nda'
      path: '/nda'
      fullPath: '/nda'
      preLoaderRoute: typeof AuthenticatedNdaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/familias': {
      id: '/_authenticated/familias'
      path: '/familias'
      fullPath: '/familias'
      preLoaderRoute: typeof AuthenticatedFamiliasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresas': {
      id: '/_authenticated/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthenticatedEmpresasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compilacoes': {
      id: '/_authenticated/compilacoes'
      path: '/compilacoes'
      fullPath: '/compilacoes'
      preLoaderRoute: typeof AuthenticatedCompilacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agentes': {
      id: '/_authenticated/agentes'
      path: '/agentes'
      fullPath: '/agentes'
      preLoaderRoute: typeof AuthenticatedAgentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aceite-termos': {
      id: '/_authenticated/aceite-termos'
      path: '/aceite-termos'
      fullPath: '/aceite-termos'
      preLoaderRoute: typeof AuthenticatedAceiteTermosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas/': {
      id: '/_authenticated/tarefas/'
      path: '/tarefas'
      fullPath: '/tarefas/'
      preLoaderRoute: typeof AuthenticatedTarefasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/representantes/': {
      id: '/_authenticated/representantes/'
      path: '/representantes'
      fullPath: '/representantes/'
      preLoaderRoute: typeof AuthenticatedRepresentantesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos/': {
      id: '/_authenticated/produtos/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof AuthenticatedProdutosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/price/': {
      id: '/_authenticated/price/'
      path: '/'
      fullPath: '/price/'
      preLoaderRoute: typeof AuthenticatedPriceIndexRouteImport
      parentRoute: typeof AuthenticatedPriceRoute
    }
    '/_authenticated/imersoes/': {
      id: '/_authenticated/imersoes/'
      path: '/imersoes'
      fullPath: '/imersoes/'
      preLoaderRoute: typeof AuthenticatedImersoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forms/': {
      id: '/_authenticated/forms/'
      path: '/forms'
      fullPath: '/forms/'
      preLoaderRoute: typeof AuthenticatedFormsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fontes/': {
      id: '/_authenticated/fontes/'
      path: '/fontes'
      fullPath: '/fontes/'
      preLoaderRoute: typeof AuthenticatedFontesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrevistas/': {
      id: '/_authenticated/entrevistas/'
      path: '/entrevistas'
      fullPath: '/entrevistas/'
      preLoaderRoute: typeof AuthenticatedEntrevistasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/backup-to-drive': {
      id: '/api/public/backup-to-drive'
      path: '/api/public/backup-to-drive'
      fullPath: '/api/public/backup-to-drive'
      preLoaderRoute: typeof ApiPublicBackupToDriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/backup-run': {
      id: '/api/public/backup-run'
      path: '/api/public/backup-run'
      fullPath: '/api/public/backup-run'
      preLoaderRoute: typeof ApiPublicBackupRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/backup-download': {
      id: '/api/public/backup-download'
      path: '/api/public/backup-download'
      fullPath: '/api/public/backup-download'
      preLoaderRoute: typeof ApiPublicBackupDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/backup-codigo': {
      id: '/api/public/backup-codigo'
      path: '/api/public/backup-codigo'
      fullPath: '/api/public/backup-codigo'
      preLoaderRoute: typeof ApiPublicBackupCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/backup-audit': {
      id: '/api/public/backup-audit'
      path: '/api/public/backup-audit'
      fullPath: '/api/public/backup-audit'
      preLoaderRoute: typeof ApiPublicBackupAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sintese/tipos': {
      id: '/_authenticated/sintese/tipos'
      path: '/sintese/tipos'
      fullPath: '/sintese/tipos'
      preLoaderRoute: typeof AuthenticatedSinteseTiposRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/representantes/performance': {
      id: '/_authenticated/representantes/performance'
      path: '/representantes/performance'
      fullPath: '/representantes/performance'
      preLoaderRoute: typeof AuthenticatedRepresentantesPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/price/tabelas': {
      id: '/_authenticated/price/tabelas'
      path: '/tabelas'
      fullPath: '/price/tabelas'
      preLoaderRoute: typeof AuthenticatedPriceTabelasRouteImport
      parentRoute: typeof AuthenticatedPriceRoute
    }
    '/_authenticated/price/competidores': {
      id: '/_authenticated/price/competidores'
      path: '/competidores'
      fullPath: '/price/competidores'
      preLoaderRoute: typeof AuthenticatedPriceCompetidoresRouteImport
      parentRoute: typeof AuthenticatedPriceRoute
    }
    '/_authenticated/price/comparativos': {
      id: '/_authenticated/price/comparativos'
      path: '/comparativos'
      fullPath: '/price/comparativos'
      preLoaderRoute: typeof AuthenticatedPriceComparativosRouteImport
      parentRoute: typeof AuthenticatedPriceRoute
    }
    '/_authenticated/imersoes/nova': {
      id: '/_authenticated/imersoes/nova'
      path: '/imersoes/nova'
      fullPath: '/imersoes/nova'
      preLoaderRoute: typeof AuthenticatedImersoesNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/imersoes/$id': {
      id: '/_authenticated/imersoes/$id'
      path: '/imersoes/$id'
      fullPath: '/imersoes/$id'
      preLoaderRoute: typeof AuthenticatedImersoesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forms/$id': {
      id: '/_authenticated/forms/$id'
      path: '/forms/$id'
      fullPath: '/forms/$id'
      preLoaderRoute: typeof AuthenticatedFormsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fontes/$id': {
      id: '/_authenticated/fontes/$id'
      path: '/fontes/$id'
      fullPath: '/fontes/$id'
      preLoaderRoute: typeof AuthenticatedFontesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrevistas/nova': {
      id: '/_authenticated/entrevistas/nova'
      path: '/entrevistas/nova'
      fullPath: '/entrevistas/nova'
      preLoaderRoute: typeof AuthenticatedEntrevistasNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrevistas/$id': {
      id: '/_authenticated/entrevistas/$id'
      path: '/entrevistas/$id'
      fullPath: '/entrevistas/$id'
      preLoaderRoute: typeof AuthenticatedEntrevistasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/novo': {
      id: '/_authenticated/clientes/novo'
      path: '/clientes/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof AuthenticatedClientesNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes-bi-batch/$repId': {
      id: '/_authenticated/clientes-bi-batch/$repId'
      path: '/clientes-bi-batch/$repId'
      fullPath: '/clientes-bi-batch/$repId'
      preLoaderRoute: typeof AuthenticatedClientesBiBatchRepIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/permissoes': {
      id: '/_authenticated/admin/permissoes'
      path: '/permissoes'
      fullPath: '/admin/permissoes'
      preLoaderRoute: typeof AuthenticatedAdminPermissoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/mfa-recuperacao': {
      id: '/_authenticated/admin/mfa-recuperacao'
      path: '/mfa-recuperacao'
      fullPath: '/admin/mfa-recuperacao'
      preLoaderRoute: typeof AuthenticatedAdminMfaRecuperacaoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/mfa-politica': {
      id: '/_authenticated/admin/mfa-politica'
      path: '/mfa-politica'
      fullPath: '/admin/mfa-politica'
      preLoaderRoute: typeof AuthenticatedAdminMfaPoliticaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/mfa': {
      id: '/_authenticated/admin/mfa'
      path: '/mfa'
      fullPath: '/admin/mfa'
      preLoaderRoute: typeof AuthenticatedAdminMfaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/lgpd': {
      id: '/_authenticated/admin/lgpd'
      path: '/lgpd'
      fullPath: '/admin/lgpd'
      preLoaderRoute: typeof AuthenticatedAdminLgpdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/gerador-performance': {
      id: '/_authenticated/admin/gerador-performance'
      path: '/gerador-performance'
      fullPath: '/admin/gerador-performance'
      preLoaderRoute: typeof AuthenticatedAdminGeradorPerformanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/evento-checkout-teste': {
      id: '/_authenticated/admin/evento-checkout-teste'
      path: '/evento-checkout-teste'
      fullPath: '/admin/evento-checkout-teste'
      preLoaderRoute: typeof AuthenticatedAdminEventoCheckoutTesteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/criterios-seguranca': {
      id: '/_authenticated/admin/criterios-seguranca'
      path: '/criterios-seguranca'
      fullPath: '/admin/criterios-seguranca'
      preLoaderRoute: typeof AuthenticatedAdminCriteriosSegurancaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/conformidade': {
      id: '/_authenticated/admin/conformidade'
      path: '/conformidade'
      fullPath: '/admin/conformidade'
      preLoaderRoute: typeof AuthenticatedAdminConformidadeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/backup': {
      id: '/_authenticated/admin/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AuthenticatedAdminBackupRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/auditoria-seguranca': {
      id: '/_authenticated/admin/auditoria-seguranca'
      path: '/auditoria-seguranca'
      fullPath: '/admin/auditoria-seguranca'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaSegurancaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mp/webhook': {
      id: '/api/public/mp/webhook'
      path: '/api/public/mp/webhook'
      fullPath: '/api/public/mp/webhook'
      preLoaderRoute: typeof ApiPublicMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mp/create-preference': {
      id: '/api/public/mp/create-preference'
      path: '/api/public/mp/create-preference'
      fullPath: '/api/public/mp/create-preference'
      preLoaderRoute: typeof ApiPublicMpCreatePreferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/weekly-security-audit': {
      id: '/api/public/hooks/weekly-security-audit'
      path: '/api/public/hooks/weekly-security-audit'
      fullPath: '/api/public/hooks/weekly-security-audit'
      preLoaderRoute: typeof ApiPublicHooksWeeklySecurityAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/mfa-deadline-check': {
      id: '/api/public/hooks/mfa-deadline-check'
      path: '/api/public/hooks/mfa-deadline-check'
      fullPath: '/api/public/hooks/mfa-deadline-check'
      preLoaderRoute: typeof ApiPublicHooksMfaDeadlineCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tarefas/b/$boardId': {
      id: '/_authenticated/tarefas/b/$boardId'
      path: '/tarefas/b/$boardId'
      fullPath: '/tarefas/b/$boardId'
      preLoaderRoute: typeof AuthenticatedTarefasBBoardIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissoes/$type/$id': {
      id: '/_authenticated/permissoes/$type/$id'
      path: '/permissoes/$type/$id'
      fullPath: '/permissoes/$type/$id'
      preLoaderRoute: typeof AuthenticatedPermissoesTypeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrevistas/$id/sessao': {
      id: '/_authenticated/entrevistas/$id/sessao'
      path: '/sessao'
      fullPath: '/entrevistas/$id/sessao'
      preLoaderRoute: typeof AuthenticatedEntrevistasIdSessaoRouteImport
      parentRoute: typeof AuthenticatedEntrevistasIdRoute
    }
    '/_authenticated/clientes/$id/editar': {
      id: '/_authenticated/clientes/$id/editar'
      path: '/editar'
      fullPath: '/clientes/$id/editar'
      preLoaderRoute: typeof AuthenticatedClientesIdEditarRouteImport
      parentRoute: typeof AuthenticatedClientesIdRoute
    }
    '/_authenticated/clientes-bi/$repId/$razao': {
      id: '/_authenticated/clientes-bi/$repId/$razao'
      path: '/clientes-bi/$repId/$razao'
      fullPath: '/clientes-bi/$repId/$razao'
      preLoaderRoute: typeof AuthenticatedClientesBiRepIdRazaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/mp/test/webhook': {
      id: '/api/public/mp/test/webhook'
      path: '/api/public/mp/test/webhook'
      fullPath: '/api/public/mp/test/webhook'
      preLoaderRoute: typeof ApiPublicMpTestWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mp/test/create-preference': {
      id: '/api/public/mp/test/create-preference'
      path: '/api/public/mp/test/create-preference'
      fullPath: '/api/public/mp/test/create-preference'
      preLoaderRoute: typeof ApiPublicMpTestCreatePreferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clientes-bi/comparar/$repId/$razao': {
      id: '/_authenticated/clientes-bi/comparar/$repId/$razao'
      path: '/clientes-bi/comparar/$repId/$razao'
      fullPath: '/clientes-bi/comparar/$repId/$razao'
      preLoaderRoute: typeof AuthenticatedClientesBiCompararRepIdRazaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditoriaSegurancaRoute: typeof AuthenticatedAdminAuditoriaSegurancaRoute
  AuthenticatedAdminBackupRoute: typeof AuthenticatedAdminBackupRoute
  AuthenticatedAdminConformidadeRoute: typeof AuthenticatedAdminConformidadeRoute
  AuthenticatedAdminCriteriosSegurancaRoute: typeof AuthenticatedAdminCriteriosSegurancaRoute
  AuthenticatedAdminEventoCheckoutTesteRoute: typeof AuthenticatedAdminEventoCheckoutTesteRoute
  AuthenticatedAdminGeradorPerformanceRoute: typeof AuthenticatedAdminGeradorPerformanceRoute
  AuthenticatedAdminLgpdRoute: typeof AuthenticatedAdminLgpdRoute
  AuthenticatedAdminMfaRoute: typeof AuthenticatedAdminMfaRoute
  AuthenticatedAdminMfaPoliticaRoute: typeof AuthenticatedAdminMfaPoliticaRoute
  AuthenticatedAdminMfaRecuperacaoRoute: typeof AuthenticatedAdminMfaRecuperacaoRoute
  AuthenticatedAdminPermissoesRoute: typeof AuthenticatedAdminPermissoesRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditoriaSegurancaRoute:
    AuthenticatedAdminAuditoriaSegurancaRoute,
  AuthenticatedAdminBackupRoute: AuthenticatedAdminBackupRoute,
  AuthenticatedAdminConformidadeRoute: AuthenticatedAdminConformidadeRoute,
  AuthenticatedAdminCriteriosSegurancaRoute:
    AuthenticatedAdminCriteriosSegurancaRoute,
  AuthenticatedAdminEventoCheckoutTesteRoute:
    AuthenticatedAdminEventoCheckoutTesteRoute,
  AuthenticatedAdminGeradorPerformanceRoute:
    AuthenticatedAdminGeradorPerformanceRoute,
  AuthenticatedAdminLgpdRoute: AuthenticatedAdminLgpdRoute,
  AuthenticatedAdminMfaRoute: AuthenticatedAdminMfaRoute,
  AuthenticatedAdminMfaPoliticaRoute: AuthenticatedAdminMfaPoliticaRoute,
  AuthenticatedAdminMfaRecuperacaoRoute: AuthenticatedAdminMfaRecuperacaoRoute,
  AuthenticatedAdminPermissoesRoute: AuthenticatedAdminPermissoesRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedPriceRouteChildren {
  AuthenticatedPriceComparativosRoute: typeof AuthenticatedPriceComparativosRoute
  AuthenticatedPriceCompetidoresRoute: typeof AuthenticatedPriceCompetidoresRoute
  AuthenticatedPriceTabelasRoute: typeof AuthenticatedPriceTabelasRoute
  AuthenticatedPriceIndexRoute: typeof AuthenticatedPriceIndexRoute
}

const AuthenticatedPriceRouteChildren: AuthenticatedPriceRouteChildren = {
  AuthenticatedPriceComparativosRoute: AuthenticatedPriceComparativosRoute,
  AuthenticatedPriceCompetidoresRoute: AuthenticatedPriceCompetidoresRoute,
  AuthenticatedPriceTabelasRoute: AuthenticatedPriceTabelasRoute,
  AuthenticatedPriceIndexRoute: AuthenticatedPriceIndexRoute,
}

const AuthenticatedPriceRouteWithChildren =
  AuthenticatedPriceRoute._addFileChildren(AuthenticatedPriceRouteChildren)

interface AuthenticatedClientesIdRouteChildren {
  AuthenticatedClientesIdEditarRoute: typeof AuthenticatedClientesIdEditarRoute
}

const AuthenticatedClientesIdRouteChildren: AuthenticatedClientesIdRouteChildren =
  {
    AuthenticatedClientesIdEditarRoute: AuthenticatedClientesIdEditarRoute,
  }

const AuthenticatedClientesIdRouteWithChildren =
  AuthenticatedClientesIdRoute._addFileChildren(
    AuthenticatedClientesIdRouteChildren,
  )

interface AuthenticatedEntrevistasIdRouteChildren {
  AuthenticatedEntrevistasIdSessaoRoute: typeof AuthenticatedEntrevistasIdSessaoRoute
}

const AuthenticatedEntrevistasIdRouteChildren: AuthenticatedEntrevistasIdRouteChildren =
  {
    AuthenticatedEntrevistasIdSessaoRoute:
      AuthenticatedEntrevistasIdSessaoRoute,
  }

const AuthenticatedEntrevistasIdRouteWithChildren =
  AuthenticatedEntrevistasIdRoute._addFileChildren(
    AuthenticatedEntrevistasIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAceiteTermosRoute: typeof AuthenticatedAceiteTermosRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAgentesRoute: typeof AuthenticatedAgentesRoute
  AuthenticatedCompilacoesRoute: typeof AuthenticatedCompilacoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmpresasRoute: typeof AuthenticatedEmpresasRoute
  AuthenticatedFamiliasRoute: typeof AuthenticatedFamiliasRoute
  AuthenticatedNdaRoute: typeof AuthenticatedNdaRoute
  AuthenticatedNovoCorpRoute: typeof AuthenticatedNovoCorpRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPerspectivasRoute: typeof AuthenticatedPerspectivasRoute
  AuthenticatedPriceRoute: typeof AuthenticatedPriceRouteWithChildren
  AuthenticatedProjecaoRoute: typeof AuthenticatedProjecaoRoute
  AuthenticatedRoteirosRoute: typeof AuthenticatedRoteirosRoute
  AuthenticatedTermosDeUsoRoute: typeof AuthenticatedTermosDeUsoRoute
  AuthenticatedVisaoRepRoute: typeof AuthenticatedVisaoRepRoute
  AuthenticatedVisaoRep2Route: typeof AuthenticatedVisaoRep2Route
  AuthenticatedClientesBiBatchRepIdRoute: typeof AuthenticatedClientesBiBatchRepIdRoute
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRouteWithChildren
  AuthenticatedClientesNovoRoute: typeof AuthenticatedClientesNovoRoute
  AuthenticatedEntrevistasIdRoute: typeof AuthenticatedEntrevistasIdRouteWithChildren
  AuthenticatedEntrevistasNovaRoute: typeof AuthenticatedEntrevistasNovaRoute
  AuthenticatedFontesIdRoute: typeof AuthenticatedFontesIdRoute
  AuthenticatedFormsIdRoute: typeof AuthenticatedFormsIdRoute
  AuthenticatedImersoesIdRoute: typeof AuthenticatedImersoesIdRoute
  AuthenticatedImersoesNovaRoute: typeof AuthenticatedImersoesNovaRoute
  AuthenticatedRepresentantesPerformanceRoute: typeof AuthenticatedRepresentantesPerformanceRoute
  AuthenticatedSinteseTiposRoute: typeof AuthenticatedSinteseTiposRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
  AuthenticatedEntrevistasIndexRoute: typeof AuthenticatedEntrevistasIndexRoute
  AuthenticatedFontesIndexRoute: typeof AuthenticatedFontesIndexRoute
  AuthenticatedFormsIndexRoute: typeof AuthenticatedFormsIndexRoute
  AuthenticatedImersoesIndexRoute: typeof AuthenticatedImersoesIndexRoute
  AuthenticatedProdutosIndexRoute: typeof AuthenticatedProdutosIndexRoute
  AuthenticatedRepresentantesIndexRoute: typeof AuthenticatedRepresentantesIndexRoute
  AuthenticatedTarefasIndexRoute: typeof AuthenticatedTarefasIndexRoute
  AuthenticatedClientesBiRepIdRazaoRoute: typeof AuthenticatedClientesBiRepIdRazaoRoute
  AuthenticatedPermissoesTypeIdRoute: typeof AuthenticatedPermissoesTypeIdRoute
  AuthenticatedTarefasBBoardIdRoute: typeof AuthenticatedTarefasBBoardIdRoute
  AuthenticatedClientesBiCompararRepIdRazaoRoute: typeof AuthenticatedClientesBiCompararRepIdRazaoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAceiteTermosRoute: AuthenticatedAceiteTermosRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAgentesRoute: AuthenticatedAgentesRoute,
  AuthenticatedCompilacoesRoute: AuthenticatedCompilacoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmpresasRoute: AuthenticatedEmpresasRoute,
  AuthenticatedFamiliasRoute: AuthenticatedFamiliasRoute,
  AuthenticatedNdaRoute: AuthenticatedNdaRoute,
  AuthenticatedNovoCorpRoute: AuthenticatedNovoCorpRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPerspectivasRoute: AuthenticatedPerspectivasRoute,
  AuthenticatedPriceRoute: AuthenticatedPriceRouteWithChildren,
  AuthenticatedProjecaoRoute: AuthenticatedProjecaoRoute,
  AuthenticatedRoteirosRoute: AuthenticatedRoteirosRoute,
  AuthenticatedTermosDeUsoRoute: AuthenticatedTermosDeUsoRoute,
  AuthenticatedVisaoRepRoute: AuthenticatedVisaoRepRoute,
  AuthenticatedVisaoRep2Route: AuthenticatedVisaoRep2Route,
  AuthenticatedClientesBiBatchRepIdRoute:
    AuthenticatedClientesBiBatchRepIdRoute,
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRouteWithChildren,
  AuthenticatedClientesNovoRoute: AuthenticatedClientesNovoRoute,
  AuthenticatedEntrevistasIdRoute: AuthenticatedEntrevistasIdRouteWithChildren,
  AuthenticatedEntrevistasNovaRoute: AuthenticatedEntrevistasNovaRoute,
  AuthenticatedFontesIdRoute: AuthenticatedFontesIdRoute,
  AuthenticatedFormsIdRoute: AuthenticatedFormsIdRoute,
  AuthenticatedImersoesIdRoute: AuthenticatedImersoesIdRoute,
  AuthenticatedImersoesNovaRoute: AuthenticatedImersoesNovaRoute,
  AuthenticatedRepresentantesPerformanceRoute:
    AuthenticatedRepresentantesPerformanceRoute,
  AuthenticatedSinteseTiposRoute: AuthenticatedSinteseTiposRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
  AuthenticatedEntrevistasIndexRoute: AuthenticatedEntrevistasIndexRoute,
  AuthenticatedFontesIndexRoute: AuthenticatedFontesIndexRoute,
  AuthenticatedFormsIndexRoute: AuthenticatedFormsIndexRoute,
  AuthenticatedImersoesIndexRoute: AuthenticatedImersoesIndexRoute,
  AuthenticatedProdutosIndexRoute: AuthenticatedProdutosIndexRoute,
  AuthenticatedRepresentantesIndexRoute: AuthenticatedRepresentantesIndexRoute,
  AuthenticatedTarefasIndexRoute: AuthenticatedTarefasIndexRoute,
  AuthenticatedClientesBiRepIdRazaoRoute:
    AuthenticatedClientesBiRepIdRazaoRoute,
  AuthenticatedPermissoesTypeIdRoute: AuthenticatedPermissoesTypeIdRoute,
  AuthenticatedTarefasBBoardIdRoute: AuthenticatedTarefasBBoardIdRoute,
  AuthenticatedClientesBiCompararRepIdRazaoRoute:
    AuthenticatedClientesBiCompararRepIdRazaoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DefinirSenhaRoute: DefinirSenhaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  EventoCheckoutRoute: EventoCheckoutRoute,
  EventoFalhaRoute: EventoFalhaRoute,
  EventoPendenteRoute: EventoPendenteRoute,
  EventoSucessoRoute: EventoSucessoRoute,
  FSlugRoute: FSlugRoute,
  RTokenRoute: RTokenRoute,
  ApiPublicBackupAuditRoute: ApiPublicBackupAuditRoute,
  ApiPublicBackupCodigoRoute: ApiPublicBackupCodigoRoute,
  ApiPublicBackupDownloadRoute: ApiPublicBackupDownloadRoute,
  ApiPublicBackupRunRoute: ApiPublicBackupRunRoute,
  ApiPublicBackupToDriveRoute: ApiPublicBackupToDriveRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksMfaDeadlineCheckRoute: ApiPublicHooksMfaDeadlineCheckRoute,
  ApiPublicHooksWeeklySecurityAuditRoute:
    ApiPublicHooksWeeklySecurityAuditRoute,
  ApiPublicMpCreatePreferenceRoute: ApiPublicMpCreatePreferenceRoute,
  ApiPublicMpWebhookRoute: ApiPublicMpWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
  ApiPublicMpTestCreatePreferenceRoute: ApiPublicMpTestCreatePreferenceRoute,
  ApiPublicMpTestWebhookRoute: ApiPublicMpTestWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
