/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as EventoSucessoRouteImport } from './routes/evento.sucesso'
import { Route as EventoPendenteRouteImport } from './routes/evento.pendente'
import { Route as EventoFalhaRouteImport } from './routes/evento.falha'
import { Route as EventoCheckoutRouteImport } from './routes/evento.checkout'
import { Route as AuthenticatedRoteirosRouteImport } from './routes/_authenticated/roteiros'
import { Route as AuthenticatedProjecaoRouteImport } from './routes/_authenticated/projecao'
import { Route as AuthenticatedPriceRouteImport } from './routes/_authenticated/price'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedPerspectivasRouteImport } from './routes/_authenticated/perspectivas'
import { Route as AuthenticatedNovoCorpRouteImport } from './routes/_authenticated/novo-corp'
import { Route as AuthenticatedNdaRouteImport } from './routes/_authenticated/nda'
import { Route as AuthenticatedFamiliasRouteImport } from './routes/_authenticated/familias'
import { Route as AuthenticatedEmpresasRouteImport } from './routes/_authenticated/empresas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompilacoesRouteImport } from './routes/_authenticated/compilacoes'
import { Route as AuthenticatedAgentesRouteImport } from './routes/_authenticated/agentes'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedRepresentantesIndexRouteImport } from './routes/_authenticated/representantes.index'
import { Route as AuthenticatedProdutosIndexRouteImport } from './routes/_authenticated/produtos.index'
import { Route as AuthenticatedImersoesIndexRouteImport } from './routes/_authenticated/imersoes.index'
import { Route as AuthenticatedEntrevistasIndexRouteImport } from './routes/_authenticated/entrevistas.index'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes.index'
import { Route as ApiPublicBackupToDriveRouteImport } from './routes/api/public/backup-to-drive'
import { Route as ApiPublicBackupRunRouteImport } from './routes/api/public/backup-run'
import { Route as ApiPublicBackupDownloadRouteImport } from './routes/api/public/backup-download'
import { Route as ApiPublicBackupCodigoRouteImport } from './routes/api/public/backup-codigo'
import { Route as ApiPublicBackupAuditRouteImport } from './routes/api/public/backup-audit'
import { Route as AuthenticatedRepresentantesPerformanceRouteImport } from './routes/_authenticated/representantes.performance'
import { Route as AuthenticatedImersoesNovaRouteImport } from './routes/_authenticated/imersoes.nova'
import { Route as AuthenticatedImersoesIdRouteImport } from './routes/_authenticated/imersoes.$id'
import { Route as AuthenticatedEntrevistasNovaRouteImport } from './routes/_authenticated/entrevistas.nova'
import { Route as AuthenticatedEntrevistasIdRouteImport } from './routes/_authenticated/entrevistas.$id'
import { Route as AuthenticatedClientesNovoRouteImport } from './routes/_authenticated/clientes.novo'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes.$id'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminPermissoesRouteImport } from './routes/_authenticated/admin.permissoes'
import { Route as AuthenticatedAdminBackupRouteImport } from './routes/_authenticated/admin.backup'
import { Route as ApiPublicMpWebhookRouteImport } from './routes/api/public/mp/webhook'
import { Route as ApiPublicMpCreatePreferenceRouteImport } from './routes/api/public/mp/create-preference'
import { Route as AuthenticatedPermissoesTypeIdRouteImport } from './routes/_authenticated/permissoes.$type.$id'
import { Route as AuthenticatedEntrevistasIdSessaoRouteImport } from './routes/_authenticated/entrevistas.$id.sessao'
import { Route as AuthenticatedClientesIdEditarRouteImport } from './routes/_authenticated/clientes.$id.editar'
import { Route as ApiPublicMpTestCreatePreferenceRouteImport } from './routes/api/public/mp/test/create-preference'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EventoSucessoRoute = EventoSucessoRouteImport.update({
  id: '/evento/sucesso',
  path: '/evento/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const EventoPendenteRoute = EventoPendenteRouteImport.update({
  id: '/evento/pendente',
  path: '/evento/pendente',
  getParentRoute: () => rootRouteImport,
} as any)
const EventoFalhaRoute = EventoFalhaRouteImport.update({
  id: '/evento/falha',
  path: '/evento/falha',
  getParentRoute: () => rootRouteImport,
} as any)
const EventoCheckoutRoute = EventoCheckoutRouteImport.update({
  id: '/evento/checkout',
  path: '/evento/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoteirosRoute = AuthenticatedRoteirosRouteImport.update({
  id: '/roteiros',
  path: '/roteiros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjecaoRoute = AuthenticatedProjecaoRouteImport.update({
  id: '/projecao',
  path: '/projecao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPriceRoute = AuthenticatedPriceRouteImport.update({
  id: '/price',
  path: '/price',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerspectivasRoute =
  AuthenticatedPerspectivasRouteImport.update({
    id: '/perspectivas',
    path: '/perspectivas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNovoCorpRoute = AuthenticatedNovoCorpRouteImport.update({
  id: '/novo-corp',
  path: '/novo-corp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNdaRoute = AuthenticatedNdaRouteImport.update({
  id: '/nda',
  path: '/nda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFamiliasRoute = AuthenticatedFamiliasRouteImport.update({
  id: '/familias',
  path: '/familias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpresasRoute = AuthenticatedEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompilacoesRoute =
  AuthenticatedCompilacoesRouteImport.update({
    id: '/compilacoes',
    path: '/compilacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgentesRoute = AuthenticatedAgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRepresentantesIndexRoute =
  AuthenticatedRepresentantesIndexRouteImport.update({
    id: '/representantes/',
    path: '/representantes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProdutosIndexRoute =
  AuthenticatedProdutosIndexRouteImport.update({
    id: '/produtos/',
    path: '/produtos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImersoesIndexRoute =
  AuthenticatedImersoesIndexRouteImport.update({
    id: '/imersoes/',
    path: '/imersoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntrevistasIndexRoute =
  AuthenticatedEntrevistasIndexRouteImport.update({
    id: '/entrevistas/',
    path: '/entrevistas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicBackupToDriveRoute = ApiPublicBackupToDriveRouteImport.update({
  id: '/api/public/backup-to-drive',
  path: '/api/public/backup-to-drive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBackupRunRoute = ApiPublicBackupRunRouteImport.update({
  id: '/api/public/backup-run',
  path: '/api/public/backup-run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBackupDownloadRoute = ApiPublicBackupDownloadRouteImport.update({
  id: '/api/public/backup-download',
  path: '/api/public/backup-download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBackupCodigoRoute = ApiPublicBackupCodigoRouteImport.update({
  id: '/api/public/backup-codigo',
  path: '/api/public/backup-codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBackupAuditRoute = ApiPublicBackupAuditRouteImport.update({
  id: '/api/public/backup-audit',
  path: '/api/public/backup-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRepresentantesPerformanceRoute =
  AuthenticatedRepresentantesPerformanceRouteImport.update({
    id: '/representantes/performance',
    path: '/representantes/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImersoesNovaRoute =
  AuthenticatedImersoesNovaRouteImport.update({
    id: '/imersoes/nova',
    path: '/imersoes/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImersoesIdRoute = AuthenticatedImersoesIdRouteImport.update({
  id: '/imersoes/$id',
  path: '/imersoes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntrevistasNovaRoute =
  AuthenticatedEntrevistasNovaRouteImport.update({
    id: '/entrevistas/nova',
    path: '/entrevistas/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntrevistasIdRoute =
  AuthenticatedEntrevistasIdRouteImport.update({
    id: '/entrevistas/$id',
    path: '/entrevistas/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesNovoRoute =
  AuthenticatedClientesNovoRouteImport.update({
    id: '/clientes/novo',
    path: '/clientes/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPermissoesRoute =
  AuthenticatedAdminPermissoesRouteImport.update({
    id: '/permissoes',
    path: '/permissoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBackupRoute =
  AuthenticatedAdminBackupRouteImport.update({
    id: '/backup',
    path: '/backup',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicMpWebhookRoute = ApiPublicMpWebhookRouteImport.update({
  id: '/api/public/mp/webhook',
  path: '/api/public/mp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpCreatePreferenceRoute =
  ApiPublicMpCreatePreferenceRouteImport.update({
    id: '/api/public/mp/create-preference',
    path: '/api/public/mp/create-preference',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPermissoesTypeIdRoute =
  AuthenticatedPermissoesTypeIdRouteImport.update({
    id: '/permissoes/$type/$id',
    path: '/permissoes/$type/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntrevistasIdSessaoRoute =
  AuthenticatedEntrevistasIdSessaoRouteImport.update({
    id: '/sessao',
    path: '/sessao',
    getParentRoute: () => AuthenticatedEntrevistasIdRoute,
  } as any)
const AuthenticatedClientesIdEditarRoute =
  AuthenticatedClientesIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedClientesIdRoute,
  } as any)
const ApiPublicMpTestCreatePreferenceRoute =
  ApiPublicMpTestCreatePreferenceRouteImport.update({
    id: '/api/public/mp/test/create-preference',
    path: '/api/public/mp/test/create-preference',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/agentes': typeof AuthenticatedAgentesRoute
  '/compilacoes': typeof AuthenticatedCompilacoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/familias': typeof AuthenticatedFamiliasRoute
  '/nda': typeof AuthenticatedNdaRoute
  '/novo-corp': typeof AuthenticatedNovoCorpRoute
  '/perspectivas': typeof AuthenticatedPerspectivasRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/price': typeof AuthenticatedPriceRoute
  '/projecao': typeof AuthenticatedProjecaoRoute
  '/roteiros': typeof AuthenticatedRoteirosRoute
  '/evento/checkout': typeof EventoCheckoutRoute
  '/evento/falha': typeof EventoFalhaRoute
  '/evento/pendente': typeof EventoPendenteRoute
  '/evento/sucesso': typeof EventoSucessoRoute
  '/r/$token': typeof RTokenRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/permissoes': typeof AuthenticatedAdminPermissoesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRouteWithChildren
  '/clientes/novo': typeof AuthenticatedClientesNovoRoute
  '/entrevistas/$id': typeof AuthenticatedEntrevistasIdRouteWithChildren
  '/entrevistas/nova': typeof AuthenticatedEntrevistasNovaRoute
  '/imersoes/$id': typeof AuthenticatedImersoesIdRoute
  '/imersoes/nova': typeof AuthenticatedImersoesNovaRoute
  '/representantes/performance': typeof AuthenticatedRepresentantesPerformanceRoute
  '/api/public/backup-audit': typeof ApiPublicBackupAuditRoute
  '/api/public/backup-codigo': typeof ApiPublicBackupCodigoRoute
  '/api/public/backup-download': typeof ApiPublicBackupDownloadRoute
  '/api/public/backup-run': typeof ApiPublicBackupRunRoute
  '/api/public/backup-to-drive': typeof ApiPublicBackupToDriveRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
  '/entrevistas/': typeof AuthenticatedEntrevistasIndexRoute
  '/imersoes/': typeof AuthenticatedImersoesIndexRoute
  '/produtos/': typeof AuthenticatedProdutosIndexRoute
  '/representantes/': typeof AuthenticatedRepresentantesIndexRoute
  '/clientes/$id/editar': typeof AuthenticatedClientesIdEditarRoute
  '/entrevistas/$id/sessao': typeof AuthenticatedEntrevistasIdSessaoRoute
  '/permissoes/$type/$id': typeof AuthenticatedPermissoesTypeIdRoute
  '/api/public/mp/create-preference': typeof ApiPublicMpCreatePreferenceRoute
  '/api/public/mp/webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/mp/test/create-preference': typeof ApiPublicMpTestCreatePreferenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/agentes': typeof AuthenticatedAgentesRoute
  '/compilacoes': typeof AuthenticatedCompilacoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/familias': typeof AuthenticatedFamiliasRoute
  '/nda': typeof AuthenticatedNdaRoute
  '/novo-corp': typeof AuthenticatedNovoCorpRoute
  '/perspectivas': typeof AuthenticatedPerspectivasRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/price': typeof AuthenticatedPriceRoute
  '/projecao': typeof AuthenticatedProjecaoRoute
  '/roteiros': typeof AuthenticatedRoteirosRoute
  '/evento/checkout': typeof EventoCheckoutRoute
  '/evento/falha': typeof EventoFalhaRoute
  '/evento/pendente': typeof EventoPendenteRoute
  '/evento/sucesso': typeof EventoSucessoRoute
  '/r/$token': typeof RTokenRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/permissoes': typeof AuthenticatedAdminPermissoesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRouteWithChildren
  '/clientes/novo': typeof AuthenticatedClientesNovoRoute
  '/entrevistas/$id': typeof AuthenticatedEntrevistasIdRouteWithChildren
  '/entrevistas/nova': typeof AuthenticatedEntrevistasNovaRoute
  '/imersoes/$id': typeof AuthenticatedImersoesIdRoute
  '/imersoes/nova': typeof AuthenticatedImersoesNovaRoute
  '/representantes/performance': typeof AuthenticatedRepresentantesPerformanceRoute
  '/api/public/backup-audit': typeof ApiPublicBackupAuditRoute
  '/api/public/backup-codigo': typeof ApiPublicBackupCodigoRoute
  '/api/public/backup-download': typeof ApiPublicBackupDownloadRoute
  '/api/public/backup-run': typeof ApiPublicBackupRunRoute
  '/api/public/backup-to-drive': typeof ApiPublicBackupToDriveRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/entrevistas': typeof AuthenticatedEntrevistasIndexRoute
  '/imersoes': typeof AuthenticatedImersoesIndexRoute
  '/produtos': typeof AuthenticatedProdutosIndexRoute
  '/representantes': typeof AuthenticatedRepresentantesIndexRoute
  '/clientes/$id/editar': typeof AuthenticatedClientesIdEditarRoute
  '/entrevistas/$id/sessao': typeof AuthenticatedEntrevistasIdSessaoRoute
  '/permissoes/$type/$id': typeof AuthenticatedPermissoesTypeIdRoute
  '/api/public/mp/create-preference': typeof ApiPublicMpCreatePreferenceRoute
  '/api/public/mp/webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/mp/test/create-preference': typeof ApiPublicMpTestCreatePreferenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/agentes': typeof AuthenticatedAgentesRoute
  '/_authenticated/compilacoes': typeof AuthenticatedCompilacoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/empresas': typeof AuthenticatedEmpresasRoute
  '/_authenticated/familias': typeof AuthenticatedFamiliasRoute
  '/_authenticated/nda': typeof AuthenticatedNdaRoute
  '/_authenticated/novo-corp': typeof AuthenticatedNovoCorpRoute
  '/_authenticated/perspectivas': typeof AuthenticatedPerspectivasRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/price': typeof AuthenticatedPriceRoute
  '/_authenticated/projecao': typeof AuthenticatedProjecaoRoute
  '/_authenticated/roteiros': typeof AuthenticatedRoteirosRoute
  '/evento/checkout': typeof EventoCheckoutRoute
  '/evento/falha': typeof EventoFalhaRoute
  '/evento/pendente': typeof EventoPendenteRoute
  '/evento/sucesso': typeof EventoSucessoRoute
  '/r/$token': typeof RTokenRoute
  '/_authenticated/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/_authenticated/admin/permissoes': typeof AuthenticatedAdminPermissoesRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRouteWithChildren
  '/_authenticated/clientes/novo': typeof AuthenticatedClientesNovoRoute
  '/_authenticated/entrevistas/$id': typeof AuthenticatedEntrevistasIdRouteWithChildren
  '/_authenticated/entrevistas/nova': typeof AuthenticatedEntrevistasNovaRoute
  '/_authenticated/imersoes/$id': typeof AuthenticatedImersoesIdRoute
  '/_authenticated/imersoes/nova': typeof AuthenticatedImersoesNovaRoute
  '/_authenticated/representantes/performance': typeof AuthenticatedRepresentantesPerformanceRoute
  '/api/public/backup-audit': typeof ApiPublicBackupAuditRoute
  '/api/public/backup-codigo': typeof ApiPublicBackupCodigoRoute
  '/api/public/backup-download': typeof ApiPublicBackupDownloadRoute
  '/api/public/backup-run': typeof ApiPublicBackupRunRoute
  '/api/public/backup-to-drive': typeof ApiPublicBackupToDriveRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/_authenticated/entrevistas/': typeof AuthenticatedEntrevistasIndexRoute
  '/_authenticated/imersoes/': typeof AuthenticatedImersoesIndexRoute
  '/_authenticated/produtos/': typeof AuthenticatedProdutosIndexRoute
  '/_authenticated/representantes/': typeof AuthenticatedRepresentantesIndexRoute
  '/_authenticated/clientes/$id/editar': typeof AuthenticatedClientesIdEditarRoute
  '/_authenticated/entrevistas/$id/sessao': typeof AuthenticatedEntrevistasIdSessaoRoute
  '/_authenticated/permissoes/$type/$id': typeof AuthenticatedPermissoesTypeIdRoute
  '/api/public/mp/create-preference': typeof ApiPublicMpCreatePreferenceRoute
  '/api/public/mp/webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/mp/test/create-preference': typeof ApiPublicMpTestCreatePreferenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/agentes'
    | '/compilacoes'
    | '/dashboard'
    | '/empresas'
    | '/familias'
    | '/nda'
    | '/novo-corp'
    | '/perspectivas'
    | '/planos'
    | '/price'
    | '/projecao'
    | '/roteiros'
    | '/evento/checkout'
    | '/evento/falha'
    | '/evento/pendente'
    | '/evento/sucesso'
    | '/r/$token'
    | '/admin/backup'
    | '/admin/permissoes'
    | '/admin/usuarios'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/entrevistas/$id'
    | '/entrevistas/nova'
    | '/imersoes/$id'
    | '/imersoes/nova'
    | '/representantes/performance'
    | '/api/public/backup-audit'
    | '/api/public/backup-codigo'
    | '/api/public/backup-download'
    | '/api/public/backup-run'
    | '/api/public/backup-to-drive'
    | '/clientes/'
    | '/entrevistas/'
    | '/imersoes/'
    | '/produtos/'
    | '/representantes/'
    | '/clientes/$id/editar'
    | '/entrevistas/$id/sessao'
    | '/permissoes/$type/$id'
    | '/api/public/mp/create-preference'
    | '/api/public/mp/webhook'
    | '/api/public/mp/test/create-preference'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/agentes'
    | '/compilacoes'
    | '/dashboard'
    | '/empresas'
    | '/familias'
    | '/nda'
    | '/novo-corp'
    | '/perspectivas'
    | '/planos'
    | '/price'
    | '/projecao'
    | '/roteiros'
    | '/evento/checkout'
    | '/evento/falha'
    | '/evento/pendente'
    | '/evento/sucesso'
    | '/r/$token'
    | '/admin/backup'
    | '/admin/permissoes'
    | '/admin/usuarios'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/entrevistas/$id'
    | '/entrevistas/nova'
    | '/imersoes/$id'
    | '/imersoes/nova'
    | '/representantes/performance'
    | '/api/public/backup-audit'
    | '/api/public/backup-codigo'
    | '/api/public/backup-download'
    | '/api/public/backup-run'
    | '/api/public/backup-to-drive'
    | '/clientes'
    | '/entrevistas'
    | '/imersoes'
    | '/produtos'
    | '/representantes'
    | '/clientes/$id/editar'
    | '/entrevistas/$id/sessao'
    | '/permissoes/$type/$id'
    | '/api/public/mp/create-preference'
    | '/api/public/mp/webhook'
    | '/api/public/mp/test/create-preference'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/agentes'
    | '/_authenticated/compilacoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/empresas'
    | '/_authenticated/familias'
    | '/_authenticated/nda'
    | '/_authenticated/novo-corp'
    | '/_authenticated/perspectivas'
    | '/_authenticated/planos'
    | '/_authenticated/price'
    | '/_authenticated/projecao'
    | '/_authenticated/roteiros'
    | '/evento/checkout'
    | '/evento/falha'
    | '/evento/pendente'
    | '/evento/sucesso'
    | '/r/$token'
    | '/_authenticated/admin/backup'
    | '/_authenticated/admin/permissoes'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/clientes/novo'
    | '/_authenticated/entrevistas/$id'
    | '/_authenticated/entrevistas/nova'
    | '/_authenticated/imersoes/$id'
    | '/_authenticated/imersoes/nova'
    | '/_authenticated/representantes/performance'
    | '/api/public/backup-audit'
    | '/api/public/backup-codigo'
    | '/api/public/backup-download'
    | '/api/public/backup-run'
    | '/api/public/backup-to-drive'
    | '/_authenticated/clientes/'
    | '/_authenticated/entrevistas/'
    | '/_authenticated/imersoes/'
    | '/_authenticated/produtos/'
    | '/_authenticated/representantes/'
    | '/_authenticated/clientes/$id/editar'
    | '/_authenticated/entrevistas/$id/sessao'
    | '/_authenticated/permissoes/$type/$id'
    | '/api/public/mp/create-preference'
    | '/api/public/mp/webhook'
    | '/api/public/mp/test/create-preference'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EventoCheckoutRoute: typeof EventoCheckoutRoute
  EventoFalhaRoute: typeof EventoFalhaRoute
  EventoPendenteRoute: typeof EventoPendenteRoute
  EventoSucessoRoute: typeof EventoSucessoRoute
  RTokenRoute: typeof RTokenRoute
  ApiPublicBackupAuditRoute: typeof ApiPublicBackupAuditRoute
  ApiPublicBackupCodigoRoute: typeof ApiPublicBackupCodigoRoute
  ApiPublicBackupDownloadRoute: typeof ApiPublicBackupDownloadRoute
  ApiPublicBackupRunRoute: typeof ApiPublicBackupRunRoute
  ApiPublicBackupToDriveRoute: typeof ApiPublicBackupToDriveRoute
  ApiPublicMpCreatePreferenceRoute: typeof ApiPublicMpCreatePreferenceRoute
  ApiPublicMpWebhookRoute: typeof ApiPublicMpWebhookRoute
  ApiPublicMpTestCreatePreferenceRoute: typeof ApiPublicMpTestCreatePreferenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evento/sucesso': {
      id: '/evento/sucesso'
      path: '/evento/sucesso'
      fullPath: '/evento/sucesso'
      preLoaderRoute: typeof EventoSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evento/pendente': {
      id: '/evento/pendente'
      path: '/evento/pendente'
      fullPath: '/evento/pendente'
      preLoaderRoute: typeof EventoPendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evento/falha': {
      id: '/evento/falha'
      path: '/evento/falha'
      fullPath: '/evento/falha'
      preLoaderRoute: typeof EventoFalhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evento/checkout': {
      id: '/evento/checkout'
      path: '/evento/checkout'
      fullPath: '/evento/checkout'
      preLoaderRoute: typeof EventoCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/roteiros': {
      id: '/_authenticated/roteiros'
      path: '/roteiros'
      fullPath: '/roteiros'
      preLoaderRoute: typeof AuthenticatedRoteirosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projecao': {
      id: '/_authenticated/projecao'
      path: '/projecao'
      fullPath: '/projecao'
      preLoaderRoute: typeof AuthenticatedProjecaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/price': {
      id: '/_authenticated/price'
      path: '/price'
      fullPath: '/price'
      preLoaderRoute: typeof AuthenticatedPriceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perspectivas': {
      id: '/_authenticated/perspectivas'
      path: '/perspectivas'
      fullPath: '/perspectivas'
      preLoaderRoute: typeof AuthenticatedPerspectivasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/novo-corp': {
      id: '/_authenticated/novo-corp'
      path: '/novo-corp'
      fullPath: '/novo-corp'
      preLoaderRoute: typeof AuthenticatedNovoCorpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nda': {
      id: '/_authenticated/nda'
      path: '/nda'
      fullPath: '/nda'
      preLoaderRoute: typeof AuthenticatedNdaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/familias': {
      id: '/_authenticated/familias'
      path: '/familias'
      fullPath: '/familias'
      preLoaderRoute: typeof AuthenticatedFamiliasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresas': {
      id: '/_authenticated/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthenticatedEmpresasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compilacoes': {
      id: '/_authenticated/compilacoes'
      path: '/compilacoes'
      fullPath: '/compilacoes'
      preLoaderRoute: typeof AuthenticatedCompilacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agentes': {
      id: '/_authenticated/agentes'
      path: '/agentes'
      fullPath: '/agentes'
      preLoaderRoute: typeof AuthenticatedAgentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/representantes/': {
      id: '/_authenticated/representantes/'
      path: '/representantes'
      fullPath: '/representantes/'
      preLoaderRoute: typeof AuthenticatedRepresentantesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos/': {
      id: '/_authenticated/produtos/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof AuthenticatedProdutosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/imersoes/': {
      id: '/_authenticated/imersoes/'
      path: '/imersoes'
      fullPath: '/imersoes/'
      preLoaderRoute: typeof AuthenticatedImersoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrevistas/': {
      id: '/_authenticated/entrevistas/'
      path: '/entrevistas'
      fullPath: '/entrevistas/'
      preLoaderRoute: typeof AuthenticatedEntrevistasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/backup-to-drive': {
      id: '/api/public/backup-to-drive'
      path: '/api/public/backup-to-drive'
      fullPath: '/api/public/backup-to-drive'
      preLoaderRoute: typeof ApiPublicBackupToDriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/backup-run': {
      id: '/api/public/backup-run'
      path: '/api/public/backup-run'
      fullPath: '/api/public/backup-run'
      preLoaderRoute: typeof ApiPublicBackupRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/backup-download': {
      id: '/api/public/backup-download'
      path: '/api/public/backup-download'
      fullPath: '/api/public/backup-download'
      preLoaderRoute: typeof ApiPublicBackupDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/backup-codigo': {
      id: '/api/public/backup-codigo'
      path: '/api/public/backup-codigo'
      fullPath: '/api/public/backup-codigo'
      preLoaderRoute: typeof ApiPublicBackupCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/backup-audit': {
      id: '/api/public/backup-audit'
      path: '/api/public/backup-audit'
      fullPath: '/api/public/backup-audit'
      preLoaderRoute: typeof ApiPublicBackupAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/representantes/performance': {
      id: '/_authenticated/representantes/performance'
      path: '/representantes/performance'
      fullPath: '/representantes/performance'
      preLoaderRoute: typeof AuthenticatedRepresentantesPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/imersoes/nova': {
      id: '/_authenticated/imersoes/nova'
      path: '/imersoes/nova'
      fullPath: '/imersoes/nova'
      preLoaderRoute: typeof AuthenticatedImersoesNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/imersoes/$id': {
      id: '/_authenticated/imersoes/$id'
      path: '/imersoes/$id'
      fullPath: '/imersoes/$id'
      preLoaderRoute: typeof AuthenticatedImersoesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrevistas/nova': {
      id: '/_authenticated/entrevistas/nova'
      path: '/entrevistas/nova'
      fullPath: '/entrevistas/nova'
      preLoaderRoute: typeof AuthenticatedEntrevistasNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrevistas/$id': {
      id: '/_authenticated/entrevistas/$id'
      path: '/entrevistas/$id'
      fullPath: '/entrevistas/$id'
      preLoaderRoute: typeof AuthenticatedEntrevistasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/novo': {
      id: '/_authenticated/clientes/novo'
      path: '/clientes/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof AuthenticatedClientesNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/permissoes': {
      id: '/_authenticated/admin/permissoes'
      path: '/permissoes'
      fullPath: '/admin/permissoes'
      preLoaderRoute: typeof AuthenticatedAdminPermissoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/backup': {
      id: '/_authenticated/admin/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AuthenticatedAdminBackupRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/mp/webhook': {
      id: '/api/public/mp/webhook'
      path: '/api/public/mp/webhook'
      fullPath: '/api/public/mp/webhook'
      preLoaderRoute: typeof ApiPublicMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mp/create-preference': {
      id: '/api/public/mp/create-preference'
      path: '/api/public/mp/create-preference'
      fullPath: '/api/public/mp/create-preference'
      preLoaderRoute: typeof ApiPublicMpCreatePreferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/permissoes/$type/$id': {
      id: '/_authenticated/permissoes/$type/$id'
      path: '/permissoes/$type/$id'
      fullPath: '/permissoes/$type/$id'
      preLoaderRoute: typeof AuthenticatedPermissoesTypeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrevistas/$id/sessao': {
      id: '/_authenticated/entrevistas/$id/sessao'
      path: '/sessao'
      fullPath: '/entrevistas/$id/sessao'
      preLoaderRoute: typeof AuthenticatedEntrevistasIdSessaoRouteImport
      parentRoute: typeof AuthenticatedEntrevistasIdRoute
    }
    '/_authenticated/clientes/$id/editar': {
      id: '/_authenticated/clientes/$id/editar'
      path: '/editar'
      fullPath: '/clientes/$id/editar'
      preLoaderRoute: typeof AuthenticatedClientesIdEditarRouteImport
      parentRoute: typeof AuthenticatedClientesIdRoute
    }
    '/api/public/mp/test/create-preference': {
      id: '/api/public/mp/test/create-preference'
      path: '/api/public/mp/test/create-preference'
      fullPath: '/api/public/mp/test/create-preference'
      preLoaderRoute: typeof ApiPublicMpTestCreatePreferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBackupRoute: typeof AuthenticatedAdminBackupRoute
  AuthenticatedAdminPermissoesRoute: typeof AuthenticatedAdminPermissoesRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBackupRoute: AuthenticatedAdminBackupRoute,
  AuthenticatedAdminPermissoesRoute: AuthenticatedAdminPermissoesRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedClientesIdRouteChildren {
  AuthenticatedClientesIdEditarRoute: typeof AuthenticatedClientesIdEditarRoute
}

const AuthenticatedClientesIdRouteChildren: AuthenticatedClientesIdRouteChildren =
  {
    AuthenticatedClientesIdEditarRoute: AuthenticatedClientesIdEditarRoute,
  }

const AuthenticatedClientesIdRouteWithChildren =
  AuthenticatedClientesIdRoute._addFileChildren(
    AuthenticatedClientesIdRouteChildren,
  )

interface AuthenticatedEntrevistasIdRouteChildren {
  AuthenticatedEntrevistasIdSessaoRoute: typeof AuthenticatedEntrevistasIdSessaoRoute
}

const AuthenticatedEntrevistasIdRouteChildren: AuthenticatedEntrevistasIdRouteChildren =
  {
    AuthenticatedEntrevistasIdSessaoRoute:
      AuthenticatedEntrevistasIdSessaoRoute,
  }

const AuthenticatedEntrevistasIdRouteWithChildren =
  AuthenticatedEntrevistasIdRoute._addFileChildren(
    AuthenticatedEntrevistasIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAgentesRoute: typeof AuthenticatedAgentesRoute
  AuthenticatedCompilacoesRoute: typeof AuthenticatedCompilacoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmpresasRoute: typeof AuthenticatedEmpresasRoute
  AuthenticatedFamiliasRoute: typeof AuthenticatedFamiliasRoute
  AuthenticatedNdaRoute: typeof AuthenticatedNdaRoute
  AuthenticatedNovoCorpRoute: typeof AuthenticatedNovoCorpRoute
  AuthenticatedPerspectivasRoute: typeof AuthenticatedPerspectivasRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedPriceRoute: typeof AuthenticatedPriceRoute
  AuthenticatedProjecaoRoute: typeof AuthenticatedProjecaoRoute
  AuthenticatedRoteirosRoute: typeof AuthenticatedRoteirosRoute
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRouteWithChildren
  AuthenticatedClientesNovoRoute: typeof AuthenticatedClientesNovoRoute
  AuthenticatedEntrevistasIdRoute: typeof AuthenticatedEntrevistasIdRouteWithChildren
  AuthenticatedEntrevistasNovaRoute: typeof AuthenticatedEntrevistasNovaRoute
  AuthenticatedImersoesIdRoute: typeof AuthenticatedImersoesIdRoute
  AuthenticatedImersoesNovaRoute: typeof AuthenticatedImersoesNovaRoute
  AuthenticatedRepresentantesPerformanceRoute: typeof AuthenticatedRepresentantesPerformanceRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
  AuthenticatedEntrevistasIndexRoute: typeof AuthenticatedEntrevistasIndexRoute
  AuthenticatedImersoesIndexRoute: typeof AuthenticatedImersoesIndexRoute
  AuthenticatedProdutosIndexRoute: typeof AuthenticatedProdutosIndexRoute
  AuthenticatedRepresentantesIndexRoute: typeof AuthenticatedRepresentantesIndexRoute
  AuthenticatedPermissoesTypeIdRoute: typeof AuthenticatedPermissoesTypeIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAgentesRoute: AuthenticatedAgentesRoute,
  AuthenticatedCompilacoesRoute: AuthenticatedCompilacoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmpresasRoute: AuthenticatedEmpresasRoute,
  AuthenticatedFamiliasRoute: AuthenticatedFamiliasRoute,
  AuthenticatedNdaRoute: AuthenticatedNdaRoute,
  AuthenticatedNovoCorpRoute: AuthenticatedNovoCorpRoute,
  AuthenticatedPerspectivasRoute: AuthenticatedPerspectivasRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedPriceRoute: AuthenticatedPriceRoute,
  AuthenticatedProjecaoRoute: AuthenticatedProjecaoRoute,
  AuthenticatedRoteirosRoute: AuthenticatedRoteirosRoute,
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRouteWithChildren,
  AuthenticatedClientesNovoRoute: AuthenticatedClientesNovoRoute,
  AuthenticatedEntrevistasIdRoute: AuthenticatedEntrevistasIdRouteWithChildren,
  AuthenticatedEntrevistasNovaRoute: AuthenticatedEntrevistasNovaRoute,
  AuthenticatedImersoesIdRoute: AuthenticatedImersoesIdRoute,
  AuthenticatedImersoesNovaRoute: AuthenticatedImersoesNovaRoute,
  AuthenticatedRepresentantesPerformanceRoute:
    AuthenticatedRepresentantesPerformanceRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
  AuthenticatedEntrevistasIndexRoute: AuthenticatedEntrevistasIndexRoute,
  AuthenticatedImersoesIndexRoute: AuthenticatedImersoesIndexRoute,
  AuthenticatedProdutosIndexRoute: AuthenticatedProdutosIndexRoute,
  AuthenticatedRepresentantesIndexRoute: AuthenticatedRepresentantesIndexRoute,
  AuthenticatedPermissoesTypeIdRoute: AuthenticatedPermissoesTypeIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EventoCheckoutRoute: EventoCheckoutRoute,
  EventoFalhaRoute: EventoFalhaRoute,
  EventoPendenteRoute: EventoPendenteRoute,
  EventoSucessoRoute: EventoSucessoRoute,
  RTokenRoute: RTokenRoute,
  ApiPublicBackupAuditRoute: ApiPublicBackupAuditRoute,
  ApiPublicBackupCodigoRoute: ApiPublicBackupCodigoRoute,
  ApiPublicBackupDownloadRoute: ApiPublicBackupDownloadRoute,
  ApiPublicBackupRunRoute: ApiPublicBackupRunRoute,
  ApiPublicBackupToDriveRoute: ApiPublicBackupToDriveRoute,
  ApiPublicMpCreatePreferenceRoute: ApiPublicMpCreatePreferenceRoute,
  ApiPublicMpWebhookRoute: ApiPublicMpWebhookRoute,
  ApiPublicMpTestCreatePreferenceRoute: ApiPublicMpTestCreatePreferenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
