
ALTER TABLE public.clients
  ADD COLUMN IF NOT EXISTS codigo_erp text,
  ADD COLUMN IF NOT EXISTS codigo_alternativo text,
  ADD COLUMN IF NOT EXISTS conso_codigo text,
  ADD COLUMN IF NOT EXISTS conso_nome text,
  ADD COLUMN IF NOT EXISTS fisica_juridica text,
  ADD COLUMN IF NOT EXISTS suframa text,
  ADD COLUMN IF NOT EXISTS cnpj text,
  ADD COLUMN IF NOT EXISTS cpf text,
  ADD COLUMN IF NOT EXISTS inscricao_estadual text,
  ADD COLUMN IF NOT EXISTS inscricao_municipal text,
  ADD COLUMN IF NOT EXISTS sigla_endereco text,
  ADD COLUMN IF NOT EXISTS numero_endereco text,
  ADD COLUMN IF NOT EXISTS complemento text,
  ADD COLUMN IF NOT EXISTS bairro text,
  ADD COLUMN IF NOT EXISTS municipio text,
  ADD COLUMN IF NOT EXISTS cep text,
  ADD COLUMN IF NOT EXISTS pais text,
  ADD COLUMN IF NOT EXISTS uf_entrega text,
  ADD COLUMN IF NOT EXISTS rua_entrega text,
  ADD COLUMN IF NOT EXISTS tipo_end_entrega text,
  ADD COLUMN IF NOT EXISTS mun_entrega text,
  ADD COLUMN IF NOT EXISTS end_entrega text,
  ADD COLUMN IF NOT EXISTS num_entrega text,
  ADD COLUMN IF NOT EXISTS bai_entrega text,
  ADD COLUMN IF NOT EXISTS cep_entrega text,
  ADD COLUMN IF NOT EXISTS rota text,
  ADD COLUMN IF NOT EXISTS cod_tabela_nl text,
  ADD COLUMN IF NOT EXISTS desc_tabela_nl text,
  ADD COLUMN IF NOT EXISTS cod_tabela_st text,
  ADD COLUMN IF NOT EXISTS desc_tabela_st text,
  ADD COLUMN IF NOT EXISTS cod_tabela_sd text,
  ADD COLUMN IF NOT EXISTS desc_tabela_sd text,
  ADD COLUMN IF NOT EXISTS obs_cliente text,
  ADD COLUMN IF NOT EXISTS info_comerciais text,
  ADD COLUMN IF NOT EXISTS cod_representante text,
  ADD COLUMN IF NOT EXISTS nome_representante_erp text,
  ADD COLUMN IF NOT EXISTS assistente text,
  ADD COLUMN IF NOT EXISTS cod_transportadora text,
  ADD COLUMN IF NOT EXISTS desc_transportadora text,
  ADD COLUMN IF NOT EXISTS tipo_frete text,
  ADD COLUMN IF NOT EXISTS cond_pagamento text,
  ADD COLUMN IF NOT EXISTS categoria_erp text,
  ADD COLUMN IF NOT EXISTS grupo_erp text,
  ADD COLUMN IF NOT EXISTS data_cadastro_erp timestamptz,
  ADD COLUMN IF NOT EXISTS outro_email text,
  ADD COLUMN IF NOT EXISTS status_erp text,
  ADD COLUMN IF NOT EXISTS pertence_grupo boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS grupo_nome text;

CREATE INDEX IF NOT EXISTS idx_clients_grupo_nome ON public.clients (company_id, grupo_nome) WHERE grupo_nome IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_clients_codigo_erp ON public.clients (company_id, codigo_erp) WHERE codigo_erp IS NOT NULL;
